// CAUTION: Generated by yy - DO NOT EDIT.

// Copyright 2016 The CC Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package cc

import (
	"fmt"
)

func ExampleAbstractDeclarator() {
	fmt.Println(exampleAST(175, "\U00100001 ( _Bool * )"))
	// Output:
	// &cc.AbstractDeclarator{
	// · Pointer: &cc.Pointer{
	// · · Token: example175.c:1:14: '*',
	// · },
	// }
}

func ExampleAbstractDeclarator_case1() {
	fmt.Println(exampleAST(176, "\U00100001 ( _Bool ( ) )"))
	// Output:
	// &cc.AbstractDeclarator{
	// · Case: 1,
	// · DirectAbstractDeclarator: &cc.DirectAbstractDeclarator{
	// · · Case: 6,
	// · · Token: example176.c:1:14: '(',
	// · · Token2: example176.c:1:16: ')',
	// · },
	// }
}

func ExampleAbstractDeclaratorOpt() {
	fmt.Println(exampleAST(177, "\U00100001 ( _Bool )") == (*AbstractDeclaratorOpt)(nil))
	// Output:
	// true
}

func ExampleAbstractDeclaratorOpt_case1() {
	fmt.Println(exampleAST(178, "\U00100001 ( _Bool * )"))
	// Output:
	// &cc.AbstractDeclaratorOpt{
	// · AbstractDeclarator: &cc.AbstractDeclarator{
	// · · Pointer: &cc.Pointer{
	// · · · Token: example178.c:1:14: '*',
	// · · },
	// · },
	// }
}

func ExampleArgumentExpressionList() {
	fmt.Println(exampleAST(8, "\U00100001 'a' ( 'b' )"))
	// Output:
	// &cc.ArgumentExpressionList{
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example8.c:1:12: CHARCONST "'b'",
	// · },
	// }
}

func ExampleArgumentExpressionList_case1() {
	fmt.Println(exampleAST(9, "\U00100001 'a' ( 'b' , 'c' )"))
	// Output:
	// &cc.ArgumentExpressionList{
	// · ArgumentExpressionList: &cc.ArgumentExpressionList{
	// · · Case: 1,
	// · · Expression: &cc.Expression{
	// · · · Case: 1,
	// · · · Token: example9.c:1:18: CHARCONST "'c'",
	// · · },
	// · · Token: example9.c:1:16: ',',
	// · },
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example9.c:1:12: CHARCONST "'b'",
	// · },
	// }
}

func ExampleArgumentExpressionListOpt() {
	fmt.Println(exampleAST(10, "\U00100001 'a' ( )") == (*ArgumentExpressionListOpt)(nil))
	// Output:
	// true
}

func ExampleArgumentExpressionListOpt_case1() {
	fmt.Println(exampleAST(11, "\U00100001 'a' ( 'b' )"))
	// Output:
	// &cc.ArgumentExpressionListOpt{
	// · ArgumentExpressionList: &cc.ArgumentExpressionList{
	// · · Expression: &cc.Expression{
	// · · · Case: 1,
	// · · · Token: example11.c:1:12: CHARCONST "'b'",
	// · · },
	// · },
	// }
}

func ExampleBlockItem() {
	fmt.Println(exampleAST(217, "\U00100002 auto a { auto ; !"))
	// Output:
	// &cc.BlockItem{
	// · Declaration: &cc.Declaration{
	// · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · Case: 3,
	// · · · · Token: example217.c:1:15: AUTO "auto",
	// · · · },
	// · · },
	// · · Token: example217.c:1:20: ';',
	// · },
	// }
}

func ExampleBlockItem_case1() {
	fmt.Println(exampleAST(218, "\U00100002 auto a { ; !"))
	// Output:
	// &cc.BlockItem{
	// · Case: 1,
	// · Statement: &cc.Statement{
	// · · Case: 2,
	// · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · Token: example218.c:1:15: ';',
	// · · },
	// · },
	// }
}

func ExampleBlockItemList() {
	fmt.Println(exampleAST(213, "\U00100002 auto a { ; !"))
	// Output:
	// &cc.BlockItemList{
	// · BlockItem: &cc.BlockItem{
	// · · Case: 1,
	// · · Statement: &cc.Statement{
	// · · · Case: 2,
	// · · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · · Token: example213.c:1:15: ';',
	// · · · },
	// · · },
	// · },
	// }
}

func ExampleBlockItemList_case1() {
	fmt.Println(exampleAST(214, "\U00100002 auto a { ; ; !"))
	// Output:
	// &cc.BlockItemList{
	// · BlockItem: &cc.BlockItem{
	// · · Case: 1,
	// · · Statement: &cc.Statement{
	// · · · Case: 2,
	// · · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · · Token: example214.c:1:15: ';',
	// · · · },
	// · · },
	// · },
	// · BlockItemList: &cc.BlockItemList{
	// · · BlockItem: &cc.BlockItem{
	// · · · Case: 1,
	// · · · Statement: &cc.Statement{
	// · · · · Case: 2,
	// · · · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · · · Token: example214.c:1:17: ';',
	// · · · · },
	// · · · },
	// · · },
	// · · Case: 1,
	// · },
	// }
}

func ExampleBlockItemListOpt() {
	fmt.Println(exampleAST(215, "\U00100002 auto a { }") == (*BlockItemListOpt)(nil))
	// Output:
	// true
}

func ExampleBlockItemListOpt_case1() {
	fmt.Println(exampleAST(216, "\U00100002 auto a { ; }"))
	// Output:
	// &cc.BlockItemListOpt{
	// · BlockItemList: &cc.BlockItemList{
	// · · BlockItem: &cc.BlockItem{
	// · · · Case: 1,
	// · · · Statement: &cc.Statement{
	// · · · · Case: 2,
	// · · · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · · · Token: example216.c:1:15: ';',
	// · · · · },
	// · · · },
	// · · },
	// · },
	// }
}

func ExampleCommaOpt() {
	fmt.Println(exampleAST(126, "\U00100002 enum { a }") == (*CommaOpt)(nil))
	// Output:
	// true
}

func ExampleCommaOpt_case1() {
	fmt.Println(exampleAST(127, "\U00100002 auto a = { 'b' , }"))
	// Output:
	// &cc.CommaOpt{
	// · Token: example127.c:1:21: ',',
	// }
}

func ExampleCompoundStatement() {
	fmt.Println(exampleAST(212, "\U00100002 auto a { }"))
	// Output:
	// &cc.CompoundStatement{
	// · Token: example212.c:1:13: '{',
	// · Token2: example212.c:1:15: '}',
	// }
}

func ExampleConstantExpression() {
	fmt.Println(exampleAST(75, "\U00100001 'a'"))
	// Output:
	// &cc.ConstantExpression{
	// · Type: int,
	// · Value: 97,
	// · Expression: &cc.Expression{
	// · · Type: int,
	// · · Value: 97,
	// · · Case: 1,
	// · · Token: example75.c:1:6: CHARCONST "'a'",
	// · },
	// }
}

func ExampleControlLine() {
	fmt.Println(exampleAST(263, "\U00100000 \n#define a "))
	// Output:
	// &cc.ControlLine{
	// · Token: example263.c:2:2: PPDEFINE,
	// · Token2: example263.c:2:9: IDENTIFIER "a",
	// }
}

func ExampleControlLine_case01() {
	fmt.Println(exampleAST(264, "\U00100000 \n#define a( ... ) "))
	// Output:
	// &cc.ControlLine{
	// · Case: 1,
	// · Token: example264.c:2:2: PPDEFINE,
	// · Token2: example264.c:2:9: IDENTIFIER_LPAREN "a(",
	// · Token3: example264.c:2:12: DDD,
	// · Token4: example264.c:2:16: ')',
	// }
}

func ExampleControlLine_case02() {
	fmt.Println(exampleAST(265, "\U00100000 \n#define a( b , ... ) "))
	// Output:
	// &cc.ControlLine{
	// · Case: 2,
	// · IdentifierList: &cc.IdentifierList{
	// · · Token: example265.c:2:12: IDENTIFIER "b",
	// · },
	// · Token: example265.c:2:2: PPDEFINE,
	// · Token2: example265.c:2:9: IDENTIFIER_LPAREN "a(",
	// · Token3: example265.c:2:14: ',',
	// · Token4: example265.c:2:16: DDD,
	// · Token5: example265.c:2:20: ')',
	// }
}

func ExampleControlLine_case03() {
	fmt.Println(exampleAST(266, "\U00100000 \n#define a( ) "))
	// Output:
	// &cc.ControlLine{
	// · Case: 3,
	// · Token: example266.c:2:2: PPDEFINE,
	// · Token2: example266.c:2:9: IDENTIFIER_LPAREN "a(",
	// · Token3: example266.c:2:12: ')',
	// }
}

func ExampleControlLine_case04() {
	fmt.Println(exampleAST(267, "\U00100000 \n#error "))
	// Output:
	// &cc.ControlLine{
	// · Case: 4,
	// · Token: example267.c:2:2: PPERROR,
	// }
}

func ExampleControlLine_case05() {
	fmt.Println(exampleAST(268, "\U00100000 \n#"))
	// Output:
	// &cc.ControlLine{
	// · Case: 5,
	// · Token: example268.c:2:2: PPHASH_NL,
	// }
}

func ExampleControlLine_case06() {
	fmt.Println(exampleAST(269, "\U00100000 \n#include other_a "))
	// Output:
	// &cc.ControlLine{
	// · Case: 6,
	// · PPTokenList: []xc.Token{ // len 1
	// · · 0: example269.c:2:10: IDENTIFIER "other_a",
	// · },
	// · Token: example269.c:2:2: PPINCLUDE,
	// · Token2: example269.c:2:18: '\n',
	// }
}

func ExampleControlLine_case07() {
	fmt.Println(exampleAST(270, "\U00100000 \n#line other_a "))
	// Output:
	// &cc.ControlLine{
	// · Case: 7,
	// · PPTokenList: []xc.Token{ // len 1
	// · · 0: example270.c:2:7: IDENTIFIER "other_a",
	// · },
	// · Token: example270.c:2:2: PPLINE,
	// · Token2: example270.c:2:15: '\n',
	// }
}

func ExampleControlLine_case08() {
	fmt.Println(exampleAST(271, "\U00100000 \n#pragma "))
	// Output:
	// &cc.ControlLine{
	// · Case: 8,
	// · Token: example271.c:2:2: PPPRAGMA,
	// }
}

func ExampleControlLine_case09() {
	fmt.Println(exampleAST(272, "\U00100000 \n#undef a "))
	// Output:
	// &cc.ControlLine{
	// · Case: 9,
	// · Token: example272.c:2:2: PPUNDEF,
	// · Token2: example272.c:2:8: IDENTIFIER "a",
	// · Token3: example272.c:2:10: '\n',
	// }
}

func ExampleControlLine_case10() {
	fmt.Println(exampleAST(273, "\U00100000 \n#define a( b ... ) "))
	// Output:
	// &cc.ControlLine{
	// · Case: 10,
	// · Token: example273.c:2:2: PPDEFINE,
	// · Token2: example273.c:2:9: IDENTIFIER_LPAREN "a(",
	// · Token3: example273.c:2:12: IDENTIFIER "b",
	// · Token4: example273.c:2:14: DDD,
	// · Token5: example273.c:2:18: ')',
	// }
}

func ExampleControlLine_case11() {
	fmt.Println(exampleAST(274, "\U00100000 \n#define a( b , c ... ) "))
	// Output:
	// &cc.ControlLine{
	// · Case: 11,
	// · IdentifierList: &cc.IdentifierList{
	// · · Token: example274.c:2:12: IDENTIFIER "b",
	// · },
	// · Token: example274.c:2:2: PPDEFINE,
	// · Token2: example274.c:2:9: IDENTIFIER_LPAREN "a(",
	// · Token3: example274.c:2:14: ',',
	// · Token4: example274.c:2:16: IDENTIFIER "c",
	// · Token5: example274.c:2:18: DDD,
	// · Token6: example274.c:2:22: ')',
	// }
}

func ExampleControlLine_case12() {
	fmt.Println(exampleAST(275, "\U00100000 \n#define "))
	// Output:
	// &cc.ControlLine{
	// · Case: 12,
	// · Token: example275.c:2:2: PPDEFINE,
	// · Token2: example275.c:2:9: '\n',
	// }
}

func ExampleControlLine_case13() {
	fmt.Println(exampleAST(276, "\U00100000 \n#undef foo(bar)"))
	// Output:
	// &cc.ControlLine{
	// · Case: 13,
	// · PPTokenList: []xc.Token{ // len 3
	// · · 0: example276.c:2:11: '(',
	// · · 1: example276.c:2:12: IDENTIFIER "bar",
	// · · 2: example276.c:2:15: ')',
	// · },
	// · Token: example276.c:2:2: PPUNDEF,
	// · Token2: example276.c:2:8: IDENTIFIER "foo",
	// · Token3: example276.c:2:16: '\n',
	// }
}

func ExampleDeclaration() {
	fmt.Println(exampleAST(76, "\U00100002 auto ;"))
	// Output:
	// &cc.Declaration{
	// · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · Case: 3,
	// · · · Token: example76.c:1:6: AUTO "auto",
	// · · },
	// · },
	// · Token: example76.c:1:11: ';',
	// }
}

func ExampleDeclarationList() {
	fmt.Println(exampleAST(237, "\U00100002 auto a auto ; {"))
	// Output:
	// &cc.DeclarationList{
	// · Declaration: &cc.Declaration{
	// · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · Case: 3,
	// · · · · Token: example237.c:1:13: AUTO "auto",
	// · · · },
	// · · },
	// · · Token: example237.c:1:18: ';',
	// · },
	// }
}

func ExampleDeclarationList_case1() {
	fmt.Println(exampleAST(238, "\U00100002 auto a auto ; auto ; {"))
	// Output:
	// &cc.DeclarationList{
	// · Declaration: &cc.Declaration{
	// · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · Case: 3,
	// · · · · Token: example238.c:1:13: AUTO "auto",
	// · · · },
	// · · },
	// · · Token: example238.c:1:18: ';',
	// · },
	// · DeclarationList: &cc.DeclarationList{
	// · · Case: 1,
	// · · Declaration: &cc.Declaration{
	// · · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · · Case: 3,
	// · · · · · Token: example238.c:1:20: AUTO "auto",
	// · · · · },
	// · · · },
	// · · · Token: example238.c:1:25: ';',
	// · · },
	// · },
	// }
}

func ExampleDeclarationListOpt() {
	fmt.Println(exampleAST(239, "\U00100002 auto a {") == (*DeclarationListOpt)(nil))
	// Output:
	// true
}

func ExampleDeclarationListOpt_case1() {
	fmt.Println(exampleAST(240, "\U00100002 auto a auto ; {"))
	// Output:
	// &cc.DeclarationListOpt{
	// · DeclarationList: &cc.DeclarationList{
	// · · Declaration: &cc.Declaration{
	// · · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · · Case: 3,
	// · · · · · Token: example240.c:1:13: AUTO "auto",
	// · · · · },
	// · · · },
	// · · · Token: example240.c:1:18: ';',
	// · · },
	// · },
	// }
}

func ExampleDeclarationSpecifiers() {
	fmt.Println(exampleAST(77, "\U00100002 auto ("))
	// Output:
	// &cc.DeclarationSpecifiers{
	// · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · Case: 3,
	// · · Token: example77.c:1:6: AUTO "auto",
	// · },
	// }
}

func ExampleDeclarationSpecifiers_case1() {
	fmt.Println(exampleAST(78, "\U00100002 _Bool ("))
	// Output:
	// &cc.DeclarationSpecifiers{
	// · Case: 1,
	// · TypeSpecifier: &cc.TypeSpecifier{
	// · · Case: 9,
	// · · Token: example78.c:1:6: BOOL "_Bool",
	// · },
	// }
}

func ExampleDeclarationSpecifiers_case2() {
	fmt.Println(exampleAST(79, "\U00100002 const ("))
	// Output:
	// &cc.DeclarationSpecifiers{
	// · Case: 2,
	// · TypeQualifier: &cc.TypeQualifier{
	// · · Token: example79.c:1:6: CONST "const",
	// · },
	// }
}

func ExampleDeclarationSpecifiers_case3() {
	fmt.Println(exampleAST(80, "\U00100002 inline ("))
	// Output:
	// &cc.DeclarationSpecifiers{
	// · Case: 3,
	// · FunctionSpecifier: &cc.FunctionSpecifier{
	// · · Token: example80.c:1:6: INLINE "inline",
	// · },
	// }
}

func ExampleDeclarationSpecifiersOpt() {
	fmt.Println(exampleAST(81, "\U00100002 auto (") == (*DeclarationSpecifiersOpt)(nil))
	// Output:
	// true
}

func ExampleDeclarationSpecifiersOpt_case1() {
	fmt.Println(exampleAST(82, "\U00100002 inline auto ("))
	// Output:
	// &cc.DeclarationSpecifiersOpt{
	// · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · Case: 3,
	// · · · Token: example82.c:1:13: AUTO "auto",
	// · · },
	// · },
	// }
}

func ExampleDeclarator() {
	fmt.Println(exampleAST(139, "\U00100002 auto a )"))
	// Output:
	// &cc.Declarator{
	// · Linkage: None,
	// · DirectDeclarator: &cc.DirectDeclarator{
	// · · Token: example139.c:1:11: IDENTIFIER "a",
	// · },
	// }
}

func ExampleDeclaratorOpt() {
	fmt.Println(exampleAST(140, "\U00100002 struct { _Bool :") == (*DeclaratorOpt)(nil))
	// Output:
	// true
}

func ExampleDeclaratorOpt_case1() {
	fmt.Println(exampleAST(141, "\U00100002 struct { _Bool a :"))
	// Output:
	// &cc.DeclaratorOpt{
	// · Declarator: &cc.Declarator{
	// · · Linkage: None,
	// · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · Token: example141.c:1:21: IDENTIFIER "a",
	// · · },
	// · },
	// }
}

func ExampleDesignation() {
	fmt.Println(exampleAST(195, "\U00100001 ( _Bool ) { . a = !"))
	// Output:
	// &cc.Designation{
	// · DesignatorList: &cc.DesignatorList{
	// · · Designator: &cc.Designator{
	// · · · Case: 1,
	// · · · Token: example195.c:1:18: '.',
	// · · · Token2: example195.c:1:20: IDENTIFIER "a",
	// · · },
	// · },
	// · Token: example195.c:1:22: '=',
	// }
}

func ExampleDesignationOpt() {
	fmt.Println(exampleAST(196, "\U00100001 ( _Bool ) { !") == (*DesignationOpt)(nil))
	// Output:
	// true
}

func ExampleDesignationOpt_case1() {
	fmt.Println(exampleAST(197, "\U00100001 ( _Bool ) { . a = !"))
	// Output:
	// &cc.DesignationOpt{
	// · Designation: &cc.Designation{
	// · · DesignatorList: &cc.DesignatorList{
	// · · · Designator: &cc.Designator{
	// · · · · Case: 1,
	// · · · · Token: example197.c:1:18: '.',
	// · · · · Token2: example197.c:1:20: IDENTIFIER "a",
	// · · · },
	// · · },
	// · · Token: example197.c:1:22: '=',
	// · },
	// }
}

func ExampleDesignator() {
	fmt.Println(exampleAST(200, "\U00100001 ( _Bool ) { [ 'a' ] ."))
	// Output:
	// &cc.Designator{
	// · ConstantExpression: &cc.ConstantExpression{
	// · · Type: int,
	// · · Value: 97,
	// · · Expression: &cc.Expression{
	// · · · Type: int,
	// · · · Value: 97,
	// · · · Case: 1,
	// · · · Token: example200.c:1:20: CHARCONST "'a'",
	// · · },
	// · },
	// · Token: example200.c:1:18: '[',
	// · Token2: example200.c:1:24: ']',
	// }
}

func ExampleDesignator_case1() {
	fmt.Println(exampleAST(201, "\U00100001 ( _Bool ) { . a ."))
	// Output:
	// &cc.Designator{
	// · Case: 1,
	// · Token: example201.c:1:18: '.',
	// · Token2: example201.c:1:20: IDENTIFIER "a",
	// }
}

func ExampleDesignatorList() {
	fmt.Println(exampleAST(198, "\U00100001 ( _Bool ) { . a ."))
	// Output:
	// &cc.DesignatorList{
	// · Designator: &cc.Designator{
	// · · Case: 1,
	// · · Token: example198.c:1:18: '.',
	// · · Token2: example198.c:1:20: IDENTIFIER "a",
	// · },
	// }
}

func ExampleDesignatorList_case1() {
	fmt.Println(exampleAST(199, "\U00100001 ( _Bool ) { . a . b ."))
	// Output:
	// &cc.DesignatorList{
	// · Designator: &cc.Designator{
	// · · Case: 1,
	// · · Token: example199.c:1:18: '.',
	// · · Token2: example199.c:1:20: IDENTIFIER "a",
	// · },
	// · DesignatorList: &cc.DesignatorList{
	// · · Case: 1,
	// · · Designator: &cc.Designator{
	// · · · Case: 1,
	// · · · Token: example199.c:1:22: '.',
	// · · · Token2: example199.c:1:24: IDENTIFIER "b",
	// · · },
	// · },
	// }
}

func ExampleDirectAbstractDeclarator() {
	fmt.Println(exampleAST(179, "\U00100001 ( _Bool ( * ) ("))
	// Output:
	// &cc.DirectAbstractDeclarator{
	// · AbstractDeclarator: &cc.AbstractDeclarator{
	// · · Pointer: &cc.Pointer{
	// · · · Token: example179.c:1:16: '*',
	// · · },
	// · },
	// · Token: example179.c:1:14: '(',
	// · Token2: example179.c:1:18: ')',
	// }
}

func ExampleDirectAbstractDeclarator_case1() {
	fmt.Println(exampleAST(180, "\U00100001 ( _Bool [ ] ("))
	// Output:
	// &cc.DirectAbstractDeclarator{
	// · Case: 1,
	// · Token: example180.c:1:14: '[',
	// · Token2: example180.c:1:16: ']',
	// }
}

func ExampleDirectAbstractDeclarator_case2() {
	fmt.Println(exampleAST(181, "\U00100001 ( _Bool [ const ] ("))
	// Output:
	// &cc.DirectAbstractDeclarator{
	// · Case: 2,
	// · Token: example181.c:1:14: '[',
	// · Token2: example181.c:1:22: ']',
	// · TypeQualifierList: &cc.TypeQualifierList{
	// · · TypeQualifier: &cc.TypeQualifier{
	// · · · Token: example181.c:1:16: CONST "const",
	// · · },
	// · },
	// }
}

func ExampleDirectAbstractDeclarator_case3() {
	fmt.Println(exampleAST(182, "\U00100001 ( _Bool [ static 'a' ] ("))
	// Output:
	// &cc.DirectAbstractDeclarator{
	// · Case: 3,
	// · Expression: &cc.Expression{
	// · · Type: int,
	// · · Value: 97,
	// · · Case: 1,
	// · · Token: example182.c:1:23: CHARCONST "'a'",
	// · },
	// · Token: example182.c:1:14: '[',
	// · Token2: example182.c:1:16: STATIC "static",
	// · Token3: example182.c:1:27: ']',
	// }
}

func ExampleDirectAbstractDeclarator_case4() {
	fmt.Println(exampleAST(183, "\U00100001 ( _Bool [ const static 'a' ] ("))
	// Output:
	// &cc.DirectAbstractDeclarator{
	// · Case: 4,
	// · Expression: &cc.Expression{
	// · · Type: int,
	// · · Value: 97,
	// · · Case: 1,
	// · · Token: example183.c:1:29: CHARCONST "'a'",
	// · },
	// · Token: example183.c:1:14: '[',
	// · Token2: example183.c:1:22: STATIC "static",
	// · Token3: example183.c:1:33: ']',
	// · TypeQualifierList: &cc.TypeQualifierList{
	// · · TypeQualifier: &cc.TypeQualifier{
	// · · · Token: example183.c:1:16: CONST "const",
	// · · },
	// · },
	// }
}

func ExampleDirectAbstractDeclarator_case5() {
	fmt.Println(exampleAST(184, "\U00100001 ( _Bool [ * ] ("))
	// Output:
	// &cc.DirectAbstractDeclarator{
	// · Case: 5,
	// · Token: example184.c:1:14: '[',
	// · Token2: example184.c:1:16: '*',
	// · Token3: example184.c:1:18: ']',
	// }
}

func ExampleDirectAbstractDeclarator_case6() {
	fmt.Println(exampleAST(186, "\U00100001 ( _Bool ( ) ("))
	// Output:
	// &cc.DirectAbstractDeclarator{
	// · Case: 6,
	// · Token: example186.c:1:14: '(',
	// · Token2: example186.c:1:16: ')',
	// }
}

func ExampleDirectAbstractDeclarator_case7() {
	fmt.Println(exampleAST(188, "\U00100001 ( _Bool ( ) ( ) ("))
	// Output:
	// &cc.DirectAbstractDeclarator{
	// · Case: 7,
	// · DirectAbstractDeclarator: &cc.DirectAbstractDeclarator{
	// · · Case: 6,
	// · · Token: example188.c:1:14: '(',
	// · · Token2: example188.c:1:16: ')',
	// · },
	// · Token: example188.c:1:18: '(',
	// · Token2: example188.c:1:20: ')',
	// }
}

func ExampleDirectAbstractDeclaratorOpt() {
	fmt.Println(exampleAST(189, "\U00100001 ( _Bool [") == (*DirectAbstractDeclaratorOpt)(nil))
	// Output:
	// true
}

func ExampleDirectAbstractDeclaratorOpt_case1() {
	fmt.Println(exampleAST(190, "\U00100001 ( _Bool ( ) ["))
	// Output:
	// &cc.DirectAbstractDeclaratorOpt{
	// · DirectAbstractDeclarator: &cc.DirectAbstractDeclarator{
	// · · Case: 6,
	// · · Token: example190.c:1:14: '(',
	// · · Token2: example190.c:1:16: ')',
	// · },
	// }
}

func ExampleDirectDeclarator() {
	fmt.Println(exampleAST(142, "\U00100002 auto a ("))
	// Output:
	// &cc.DirectDeclarator{
	// · Token: example142.c:1:11: IDENTIFIER "a",
	// }
}

func ExampleDirectDeclarator_case1() {
	fmt.Println(exampleAST(143, "\U00100002 auto ( a ) ("))
	// Output:
	// &cc.DirectDeclarator{
	// · Case: 1,
	// · Declarator: &cc.Declarator{
	// · · Linkage: None,
	// · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · Token: example143.c:1:13: IDENTIFIER "a",
	// · · },
	// · },
	// · Token: example143.c:1:11: '(',
	// · Token2: example143.c:1:15: ')',
	// }
}

func ExampleDirectDeclarator_case2() {
	fmt.Println(exampleAST(144, "\U00100002 auto a [ ] ("))
	// Output:
	// &cc.DirectDeclarator{
	// · Case: 2,
	// · DirectDeclarator: &cc.DirectDeclarator{
	// · · Token: example144.c:1:11: IDENTIFIER "a",
	// · },
	// · Token: example144.c:1:13: '[',
	// · Token2: example144.c:1:15: ']',
	// }
}

func ExampleDirectDeclarator_case3() {
	fmt.Println(exampleAST(145, "\U00100002 auto a [ static 'b' ] ("))
	// Output:
	// &cc.DirectDeclarator{
	// · Case: 3,
	// · DirectDeclarator: &cc.DirectDeclarator{
	// · · Token: example145.c:1:11: IDENTIFIER "a",
	// · },
	// · Expression: &cc.Expression{
	// · · Type: int,
	// · · Value: 98,
	// · · Case: 1,
	// · · Token: example145.c:1:22: CHARCONST "'b'",
	// · },
	// · Token: example145.c:1:13: '[',
	// · Token2: example145.c:1:15: STATIC "static",
	// · Token3: example145.c:1:26: ']',
	// }
}

func ExampleDirectDeclarator_case4() {
	fmt.Println(exampleAST(146, "\U00100002 auto a [ const static 'b' ] ("))
	// Output:
	// &cc.DirectDeclarator{
	// · Case: 4,
	// · DirectDeclarator: &cc.DirectDeclarator{
	// · · Token: example146.c:1:11: IDENTIFIER "a",
	// · },
	// · Expression: &cc.Expression{
	// · · Type: int,
	// · · Value: 98,
	// · · Case: 1,
	// · · Token: example146.c:1:28: CHARCONST "'b'",
	// · },
	// · Token: example146.c:1:13: '[',
	// · Token2: example146.c:1:21: STATIC "static",
	// · Token3: example146.c:1:32: ']',
	// · TypeQualifierList: &cc.TypeQualifierList{
	// · · TypeQualifier: &cc.TypeQualifier{
	// · · · Token: example146.c:1:15: CONST "const",
	// · · },
	// · },
	// }
}

func ExampleDirectDeclarator_case5() {
	fmt.Println(exampleAST(147, "\U00100002 auto a [ * ] ("))
	// Output:
	// &cc.DirectDeclarator{
	// · Case: 5,
	// · DirectDeclarator: &cc.DirectDeclarator{
	// · · Token: example147.c:1:11: IDENTIFIER "a",
	// · },
	// · Token: example147.c:1:13: '[',
	// · Token2: example147.c:1:15: '*',
	// · Token3: example147.c:1:17: ']',
	// }
}

func ExampleDirectDeclarator_case6() {
	fmt.Println(exampleAST(149, "\U00100002 auto a ( auto ) ("))
	// Output:
	// &cc.DirectDeclarator{
	// · Case: 6,
	// · DirectDeclarator: &cc.DirectDeclarator{
	// · · Token: example149.c:1:11: IDENTIFIER "a",
	// · },
	// · ParameterTypeList: &cc.ParameterTypeList{
	// · · ParameterList: &cc.ParameterList{
	// · · · ParameterDeclaration: &cc.ParameterDeclaration{
	// · · · · Case: 1,
	// · · · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · · · Case: 3,
	// · · · · · · Token: example149.c:1:15: AUTO "auto",
	// · · · · · },
	// · · · · },
	// · · · },
	// · · },
	// · },
	// · Token: example149.c:1:13: '(',
	// · Token2: example149.c:1:20: ')',
	// }
}

func ExampleDirectDeclarator_case7() {
	fmt.Println(exampleAST(150, "\U00100002 auto a ( ) ("))
	// Output:
	// &cc.DirectDeclarator{
	// · Case: 7,
	// · DirectDeclarator: &cc.DirectDeclarator{
	// · · Token: example150.c:1:11: IDENTIFIER "a",
	// · },
	// · Token: example150.c:1:13: '(',
	// · Token2: example150.c:1:15: ')',
	// }
}

func ExampleElifGroup() {
	fmt.Println(exampleAST(258, "\U00100000 \n#if other_a  \n#elif other_b  \n#elif"))
	// Output:
	// &cc.ElifGroup{
	// · PPTokenList: []xc.Token{ // len 1
	// · · 0: example258.c:3:7: IDENTIFIER "other_b",
	// · },
	// · Token: example258.c:3:2: PPELIF,
	// · Token2: example258.c:3:16: '\n',
	// }
}

func ExampleElifGroupList() {
	fmt.Println(exampleAST(254, "\U00100000 \n#if other_a  \n#elif other_b  \n#elif"))
	// Output:
	// &cc.ElifGroupList{
	// · ElifGroup: &cc.ElifGroup{
	// · · PPTokenList: []xc.Token{ // len 1
	// · · · 0: example254.c:3:7: IDENTIFIER "other_b",
	// · · },
	// · · Token: example254.c:3:2: PPELIF,
	// · · Token2: example254.c:3:16: '\n',
	// · },
	// }
}

func ExampleElifGroupList_case1() {
	fmt.Println(exampleAST(255, "\U00100000 \n#if other_a  \n#elif other_b  \n#elif other_c  \n#elif"))
	// Output:
	// &cc.ElifGroupList{
	// · ElifGroup: &cc.ElifGroup{
	// · · PPTokenList: []xc.Token{ // len 1
	// · · · 0: example255.c:3:7: IDENTIFIER "other_b",
	// · · },
	// · · Token: example255.c:3:2: PPELIF,
	// · · Token2: example255.c:3:16: '\n',
	// · },
	// · ElifGroupList: &cc.ElifGroupList{
	// · · Case: 1,
	// · · ElifGroup: &cc.ElifGroup{
	// · · · PPTokenList: []xc.Token{ // len 1
	// · · · · 0: example255.c:4:7: IDENTIFIER "other_c",
	// · · · },
	// · · · Token: example255.c:4:2: PPELIF,
	// · · · Token2: example255.c:4:16: '\n',
	// · · },
	// · },
	// }
}

func ExampleElifGroupListOpt() {
	fmt.Println(exampleAST(256, "\U00100000 \n#if other_a  \n#else") == (*ElifGroupListOpt)(nil))
	// Output:
	// true
}

func ExampleElifGroupListOpt_case1() {
	fmt.Println(exampleAST(257, "\U00100000 \n#if other_a  \n#elif other_b  \n#else"))
	// Output:
	// &cc.ElifGroupListOpt{
	// · ElifGroupList: &cc.ElifGroupList{
	// · · ElifGroup: &cc.ElifGroup{
	// · · · PPTokenList: []xc.Token{ // len 1
	// · · · · 0: example257.c:3:7: IDENTIFIER "other_b",
	// · · · },
	// · · · Token: example257.c:3:2: PPELIF,
	// · · · Token2: example257.c:3:16: '\n',
	// · · },
	// · },
	// }
}

func ExampleElseGroup() {
	fmt.Println(exampleAST(259, "\U00100000 \n#if other_a  \n#else  \n#endif"))
	// Output:
	// &cc.ElseGroup{
	// · Token: example259.c:3:2: PPELSE,
	// · Token2: example259.c:3:8: '\n',
	// }
}

func ExampleElseGroupOpt() {
	fmt.Println(exampleAST(260, "\U00100000 \n#if other_a  \n#endif") == (*ElseGroupOpt)(nil))
	// Output:
	// true
}

func ExampleElseGroupOpt_case1() {
	fmt.Println(exampleAST(261, "\U00100000 \n#if other_a  \n#else  \n#endif"))
	// Output:
	// &cc.ElseGroupOpt{
	// · ElseGroup: &cc.ElseGroup{
	// · · Token: example261.c:3:2: PPELSE,
	// · · Token2: example261.c:3:8: '\n',
	// · },
	// }
}

func ExampleEndifLine() {
	fmt.Println(exampleAST(262, "\U00100000 \n#if other_a  \n#endif"))
	// Output:
	// &cc.EndifLine{
	// · Token: example262.c:3:2: PPENDIF,
	// }
}

func ExampleEnumSpecifier() {
	fmt.Println(exampleAST(129, "\U00100002 enum { a } ("))
	// Output:
	// &cc.EnumSpecifier{
	// · EnumeratorList: &cc.EnumeratorList{
	// · · Enumerator: &cc.Enumerator{
	// · · · EnumerationConstant: &cc.EnumerationConstant{
	// · · · · Token: example129.c:1:13: IDENTIFIER "a",
	// · · · },
	// · · },
	// · },
	// · Token: example129.c:1:6: ENUM "enum",
	// · Token2: example129.c:1:11: '{',
	// · Token3: example129.c:1:15: '}',
	// }
}

func ExampleEnumSpecifier_case1() {
	fmt.Println(exampleAST(130, "\U00100002 enum a ("))
	// Output:
	// &cc.EnumSpecifier{
	// · Case: 1,
	// · Token: example130.c:1:6: ENUM "enum",
	// · Token2: example130.c:1:11: IDENTIFIER "a",
	// }
}

func ExampleEnumerationConstant() {
	fmt.Println(exampleAST(7, "\U00100002 enum { a ,"))
	// Output:
	// &cc.EnumerationConstant{
	// · Token: example7.c:1:13: IDENTIFIER "a",
	// }
}

func ExampleEnumerator() {
	fmt.Println(exampleAST(133, "\U00100002 enum { a ,"))
	// Output:
	// &cc.Enumerator{
	// · EnumerationConstant: &cc.EnumerationConstant{
	// · · Token: example133.c:1:13: IDENTIFIER "a",
	// · },
	// }
}

func ExampleEnumerator_case1() {
	fmt.Println(exampleAST(134, "\U00100002 enum { a = 'b' ,"))
	// Output:
	// &cc.Enumerator{
	// · Case: 1,
	// · ConstantExpression: &cc.ConstantExpression{
	// · · Type: int,
	// · · Value: 98,
	// · · Expression: &cc.Expression{
	// · · · Type: int,
	// · · · Value: 98,
	// · · · Case: 1,
	// · · · Token: example134.c:1:17: CHARCONST "'b'",
	// · · },
	// · },
	// · EnumerationConstant: &cc.EnumerationConstant{
	// · · Token: example134.c:1:13: IDENTIFIER "a",
	// · },
	// · Token: example134.c:1:15: '=',
	// }
}

func ExampleEnumeratorList() {
	fmt.Println(exampleAST(131, "\U00100002 enum { a ,"))
	// Output:
	// &cc.EnumeratorList{
	// · Enumerator: &cc.Enumerator{
	// · · EnumerationConstant: &cc.EnumerationConstant{
	// · · · Token: example131.c:1:13: IDENTIFIER "a",
	// · · },
	// · },
	// }
}

func ExampleEnumeratorList_case1() {
	fmt.Println(exampleAST(132, "\U00100002 enum { a , b ,"))
	// Output:
	// &cc.EnumeratorList{
	// · Enumerator: &cc.Enumerator{
	// · · EnumerationConstant: &cc.EnumerationConstant{
	// · · · Token: example132.c:1:13: IDENTIFIER "a",
	// · · },
	// · },
	// · EnumeratorList: &cc.EnumeratorList{
	// · · Case: 1,
	// · · Enumerator: &cc.Enumerator{
	// · · · EnumerationConstant: &cc.EnumerationConstant{
	// · · · · Token: example132.c:1:17: IDENTIFIER "b",
	// · · · },
	// · · },
	// · · Token: example132.c:1:15: ',',
	// · },
	// }
}

func ExampleExpression() {
	fmt.Println(exampleAST(12, "\U00100001 a"))
	// Output:
	// &cc.Expression{
	// · Token: example12.c:1:6: IDENTIFIER "a",
	// }
}

func ExampleExpression_case01() {
	fmt.Println(exampleAST(13, "\U00100001 'a'"))
	// Output:
	// &cc.Expression{
	// · Case: 1,
	// · Token: example13.c:1:6: CHARCONST "'a'",
	// }
}

func ExampleExpression_case02() {
	fmt.Println(exampleAST(14, "\U00100001 1.97"))
	// Output:
	// &cc.Expression{
	// · Case: 2,
	// · Token: example14.c:1:6: FLOATCONST "1.97",
	// }
}

func ExampleExpression_case03() {
	fmt.Println(exampleAST(15, "\U00100001 97"))
	// Output:
	// &cc.Expression{
	// · Case: 3,
	// · Token: example15.c:1:6: INTCONST "97",
	// }
}

func ExampleExpression_case04() {
	fmt.Println(exampleAST(16, "\U00100001 L'a'"))
	// Output:
	// &cc.Expression{
	// · Case: 4,
	// · Token: example16.c:1:6: LONGCHARCONST "L'a'",
	// }
}

func ExampleExpression_case05() {
	fmt.Println(exampleAST(17, "\U00100001 L\"a\""))
	// Output:
	// &cc.Expression{
	// · Case: 5,
	// · Token: example17.c:1:6: LONGSTRINGLITERAL "L\"a\"",
	// }
}

func ExampleExpression_case06() {
	fmt.Println(exampleAST(18, "\U00100001 \"a\""))
	// Output:
	// &cc.Expression{
	// · Case: 6,
	// · Token: example18.c:1:6: STRINGLITERAL "\"a\"",
	// }
}

func ExampleExpression_case07() {
	fmt.Println(exampleAST(19, "\U00100001 ( 'a' )"))
	// Output:
	// &cc.Expression{
	// · Case: 7,
	// · ExpressionList: &cc.ExpressionList{
	// · · Expression: &cc.Expression{
	// · · · Case: 1,
	// · · · Token: example19.c:1:8: CHARCONST "'a'",
	// · · },
	// · },
	// · Token: example19.c:1:6: '(',
	// · Token2: example19.c:1:12: ')',
	// }
}

func ExampleExpression_case08() {
	fmt.Println(exampleAST(20, "\U00100001 'a' [ 'b' ]"))
	// Output:
	// &cc.Expression{
	// · Case: 8,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example20.c:1:6: CHARCONST "'a'",
	// · },
	// · ExpressionList: &cc.ExpressionList{
	// · · Expression: &cc.Expression{
	// · · · Case: 1,
	// · · · Token: example20.c:1:12: CHARCONST "'b'",
	// · · },
	// · },
	// · Token: example20.c:1:10: '[',
	// · Token2: example20.c:1:16: ']',
	// }
}

func ExampleExpression_case09() {
	fmt.Println(exampleAST(21, "\U00100001 'a' ( )"))
	// Output:
	// &cc.Expression{
	// · Case: 9,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example21.c:1:6: CHARCONST "'a'",
	// · },
	// · Token: example21.c:1:10: '(',
	// · Token2: example21.c:1:12: ')',
	// }
}

func ExampleExpression_case10() {
	fmt.Println(exampleAST(22, "\U00100001 'a' . b"))
	// Output:
	// &cc.Expression{
	// · Case: 10,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example22.c:1:6: CHARCONST "'a'",
	// · },
	// · Token: example22.c:1:10: '.',
	// · Token2: example22.c:1:12: IDENTIFIER "b",
	// }
}

func ExampleExpression_case11() {
	fmt.Println(exampleAST(23, "\U00100001 'a' -> b"))
	// Output:
	// &cc.Expression{
	// · Case: 11,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example23.c:1:6: CHARCONST "'a'",
	// · },
	// · Token: example23.c:1:10: ARROW,
	// · Token2: example23.c:1:13: IDENTIFIER "b",
	// }
}

func ExampleExpression_case12() {
	fmt.Println(exampleAST(24, "\U00100001 'a' ++"))
	// Output:
	// &cc.Expression{
	// · Case: 12,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example24.c:1:6: CHARCONST "'a'",
	// · },
	// · Token: example24.c:1:10: INC,
	// }
}

func ExampleExpression_case13() {
	fmt.Println(exampleAST(25, "\U00100001 'a' --"))
	// Output:
	// &cc.Expression{
	// · Case: 13,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example25.c:1:6: CHARCONST "'a'",
	// · },
	// · Token: example25.c:1:10: DEC,
	// }
}

func ExampleExpression_case14() {
	fmt.Println(exampleAST(26, "\U00100001 ( _Bool ) { 'a' }"))
	// Output:
	// &cc.Expression{
	// · Case: 14,
	// · InitializerList: &cc.InitializerList{
	// · · Initializer: &cc.Initializer{
	// · · · Expression: &cc.Expression{
	// · · · · Type: int,
	// · · · · Value: 97,
	// · · · · Case: 1,
	// · · · · Token: example26.c:1:18: CHARCONST "'a'",
	// · · · },
	// · · },
	// · },
	// · Token: example26.c:1:6: '(',
	// · Token2: example26.c:1:14: ')',
	// · Token3: example26.c:1:16: '{',
	// · Token4: example26.c:1:22: '}',
	// · TypeName: &cc.TypeName{
	// · · Type: bool,
	// · · SpecifierQualifierList: &cc.SpecifierQualifierList{
	// · · · TypeSpecifier: &cc.TypeSpecifier{
	// · · · · Case: 9,
	// · · · · Token: example26.c:1:8: BOOL "_Bool",
	// · · · },
	// · · },
	// · },
	// }
}

func ExampleExpression_case15() {
	fmt.Println(exampleAST(27, "\U00100001 ++ 'a'"))
	// Output:
	// &cc.Expression{
	// · Case: 15,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example27.c:1:9: CHARCONST "'a'",
	// · },
	// · Token: example27.c:1:6: INC,
	// }
}

func ExampleExpression_case16() {
	fmt.Println(exampleAST(28, "\U00100001 -- 'a'"))
	// Output:
	// &cc.Expression{
	// · Case: 16,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example28.c:1:9: CHARCONST "'a'",
	// · },
	// · Token: example28.c:1:6: DEC,
	// }
}

func ExampleExpression_case17() {
	fmt.Println(exampleAST(29, "\U00100001 & 'a'"))
	// Output:
	// &cc.Expression{
	// · Case: 17,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example29.c:1:8: CHARCONST "'a'",
	// · },
	// · Token: example29.c:1:6: '&',
	// }
}

func ExampleExpression_case18() {
	fmt.Println(exampleAST(30, "\U00100001 * 'a'"))
	// Output:
	// &cc.Expression{
	// · Case: 18,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example30.c:1:8: CHARCONST "'a'",
	// · },
	// · Token: example30.c:1:6: '*',
	// }
}

func ExampleExpression_case19() {
	fmt.Println(exampleAST(31, "\U00100001 + 'a'"))
	// Output:
	// &cc.Expression{
	// · Case: 19,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example31.c:1:8: CHARCONST "'a'",
	// · },
	// · Token: example31.c:1:6: '+',
	// }
}

func ExampleExpression_case20() {
	fmt.Println(exampleAST(32, "\U00100001 - 'a'"))
	// Output:
	// &cc.Expression{
	// · Case: 20,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example32.c:1:8: CHARCONST "'a'",
	// · },
	// · Token: example32.c:1:6: '-',
	// }
}

func ExampleExpression_case21() {
	fmt.Println(exampleAST(33, "\U00100001 ~ 'a'"))
	// Output:
	// &cc.Expression{
	// · Case: 21,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example33.c:1:8: CHARCONST "'a'",
	// · },
	// · Token: example33.c:1:6: '~',
	// }
}

func ExampleExpression_case22() {
	fmt.Println(exampleAST(34, "\U00100001 ! 'a'"))
	// Output:
	// &cc.Expression{
	// · Case: 22,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example34.c:1:8: CHARCONST "'a'",
	// · },
	// · Token: example34.c:1:6: '!',
	// }
}

func ExampleExpression_case23() {
	fmt.Println(exampleAST(35, "\U00100001 sizeof 'a'"))
	// Output:
	// &cc.Expression{
	// · Case: 23,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example35.c:1:13: CHARCONST "'a'",
	// · },
	// · Token: example35.c:1:6: SIZEOF "sizeof",
	// }
}

func ExampleExpression_case24() {
	fmt.Println(exampleAST(36, "\U00100001 sizeof ( _Bool )"))
	// Output:
	// &cc.Expression{
	// · Case: 24,
	// · Token: example36.c:1:6: SIZEOF "sizeof",
	// · Token2: example36.c:1:13: '(',
	// · Token3: example36.c:1:21: ')',
	// · TypeName: &cc.TypeName{
	// · · Type: bool,
	// · · SpecifierQualifierList: &cc.SpecifierQualifierList{
	// · · · TypeSpecifier: &cc.TypeSpecifier{
	// · · · · Case: 9,
	// · · · · Token: example36.c:1:15: BOOL "_Bool",
	// · · · },
	// · · },
	// · },
	// }
}

func ExampleExpression_case25() {
	fmt.Println(exampleAST(37, "\U00100001 ( _Bool ) 'a'"))
	// Output:
	// &cc.Expression{
	// · Case: 25,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example37.c:1:16: CHARCONST "'a'",
	// · },
	// · Token: example37.c:1:6: '(',
	// · Token2: example37.c:1:14: ')',
	// · TypeName: &cc.TypeName{
	// · · Type: bool,
	// · · SpecifierQualifierList: &cc.SpecifierQualifierList{
	// · · · TypeSpecifier: &cc.TypeSpecifier{
	// · · · · Case: 9,
	// · · · · Token: example37.c:1:8: BOOL "_Bool",
	// · · · },
	// · · },
	// · },
	// }
}

func ExampleExpression_case26() {
	fmt.Println(exampleAST(38, "\U00100001 'a' * 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 26,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example38.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example38.c:1:12: CHARCONST "'b'",
	// · },
	// · Token: example38.c:1:10: '*',
	// }
}

func ExampleExpression_case27() {
	fmt.Println(exampleAST(39, "\U00100001 'a' / 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 27,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example39.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example39.c:1:12: CHARCONST "'b'",
	// · },
	// · Token: example39.c:1:10: '/',
	// }
}

func ExampleExpression_case28() {
	fmt.Println(exampleAST(40, "\U00100001 'a' % 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 28,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example40.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example40.c:1:12: CHARCONST "'b'",
	// · },
	// · Token: example40.c:1:10: '%',
	// }
}

func ExampleExpression_case29() {
	fmt.Println(exampleAST(41, "\U00100001 'a' + 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 29,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example41.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example41.c:1:12: CHARCONST "'b'",
	// · },
	// · Token: example41.c:1:10: '+',
	// }
}

func ExampleExpression_case30() {
	fmt.Println(exampleAST(42, "\U00100001 'a' - 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 30,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example42.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example42.c:1:12: CHARCONST "'b'",
	// · },
	// · Token: example42.c:1:10: '-',
	// }
}

func ExampleExpression_case31() {
	fmt.Println(exampleAST(43, "\U00100001 'a' << 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 31,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example43.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example43.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example43.c:1:10: LSH,
	// }
}

func ExampleExpression_case32() {
	fmt.Println(exampleAST(44, "\U00100001 'a' >> 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 32,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example44.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example44.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example44.c:1:10: RSH,
	// }
}

func ExampleExpression_case33() {
	fmt.Println(exampleAST(45, "\U00100001 'a' < 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 33,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example45.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example45.c:1:12: CHARCONST "'b'",
	// · },
	// · Token: example45.c:1:10: '<',
	// }
}

func ExampleExpression_case34() {
	fmt.Println(exampleAST(46, "\U00100001 'a' > 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 34,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example46.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example46.c:1:12: CHARCONST "'b'",
	// · },
	// · Token: example46.c:1:10: '>',
	// }
}

func ExampleExpression_case35() {
	fmt.Println(exampleAST(47, "\U00100001 'a' <= 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 35,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example47.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example47.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example47.c:1:10: LEQ,
	// }
}

func ExampleExpression_case36() {
	fmt.Println(exampleAST(48, "\U00100001 'a' >= 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 36,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example48.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example48.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example48.c:1:10: GEQ,
	// }
}

func ExampleExpression_case37() {
	fmt.Println(exampleAST(49, "\U00100001 'a' == 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 37,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example49.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example49.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example49.c:1:10: EQ,
	// }
}

func ExampleExpression_case38() {
	fmt.Println(exampleAST(50, "\U00100001 'a' != 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 38,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example50.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example50.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example50.c:1:10: NEQ,
	// }
}

func ExampleExpression_case39() {
	fmt.Println(exampleAST(51, "\U00100001 'a' & 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 39,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example51.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example51.c:1:12: CHARCONST "'b'",
	// · },
	// · Token: example51.c:1:10: '&',
	// }
}

func ExampleExpression_case40() {
	fmt.Println(exampleAST(52, "\U00100001 'a' ^ 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 40,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example52.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example52.c:1:12: CHARCONST "'b'",
	// · },
	// · Token: example52.c:1:10: '^',
	// }
}

func ExampleExpression_case41() {
	fmt.Println(exampleAST(53, "\U00100001 'a' | 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 41,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example53.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example53.c:1:12: CHARCONST "'b'",
	// · },
	// · Token: example53.c:1:10: '|',
	// }
}

func ExampleExpression_case42() {
	fmt.Println(exampleAST(54, "\U00100001 'a' && 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 42,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example54.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example54.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example54.c:1:10: ANDAND,
	// }
}

func ExampleExpression_case43() {
	fmt.Println(exampleAST(55, "\U00100001 'a' || 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 43,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example55.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example55.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example55.c:1:10: OROR,
	// }
}

func ExampleExpression_case44() {
	fmt.Println(exampleAST(56, "\U00100001 'a' ? 'b' : 'c'"))
	// Output:
	// &cc.Expression{
	// · Case: 44,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example56.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example56.c:1:18: CHARCONST "'c'",
	// · },
	// · ExpressionList: &cc.ExpressionList{
	// · · Expression: &cc.Expression{
	// · · · Case: 1,
	// · · · Token: example56.c:1:12: CHARCONST "'b'",
	// · · },
	// · },
	// · Token: example56.c:1:10: '?',
	// · Token2: example56.c:1:16: ':',
	// }
}

func ExampleExpression_case45() {
	fmt.Println(exampleAST(57, "\U00100001 'a' = 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 45,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example57.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example57.c:1:12: CHARCONST "'b'",
	// · },
	// · Token: example57.c:1:10: '=',
	// }
}

func ExampleExpression_case46() {
	fmt.Println(exampleAST(58, "\U00100001 'a' *= 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 46,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example58.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example58.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example58.c:1:10: MULASSIGN,
	// }
}

func ExampleExpression_case47() {
	fmt.Println(exampleAST(59, "\U00100001 'a' /= 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 47,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example59.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example59.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example59.c:1:10: DIVASSIGN,
	// }
}

func ExampleExpression_case48() {
	fmt.Println(exampleAST(60, "\U00100001 'a' %= 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 48,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example60.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example60.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example60.c:1:10: MODASSIGN,
	// }
}

func ExampleExpression_case49() {
	fmt.Println(exampleAST(61, "\U00100001 'a' += 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 49,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example61.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example61.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example61.c:1:10: ADDASSIGN,
	// }
}

func ExampleExpression_case50() {
	fmt.Println(exampleAST(62, "\U00100001 'a' -= 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 50,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example62.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example62.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example62.c:1:10: SUBASSIGN,
	// }
}

func ExampleExpression_case51() {
	fmt.Println(exampleAST(63, "\U00100001 'a' <<= 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 51,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example63.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example63.c:1:14: CHARCONST "'b'",
	// · },
	// · Token: example63.c:1:10: LSHASSIGN,
	// }
}

func ExampleExpression_case52() {
	fmt.Println(exampleAST(64, "\U00100001 'a' >>= 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 52,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example64.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example64.c:1:14: CHARCONST "'b'",
	// · },
	// · Token: example64.c:1:10: RSHASSIGN,
	// }
}

func ExampleExpression_case53() {
	fmt.Println(exampleAST(65, "\U00100001 'a' &= 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 53,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example65.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example65.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example65.c:1:10: ANDASSIGN,
	// }
}

func ExampleExpression_case54() {
	fmt.Println(exampleAST(66, "\U00100001 'a' ^= 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 54,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example66.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example66.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example66.c:1:10: XORASSIGN,
	// }
}

func ExampleExpression_case55() {
	fmt.Println(exampleAST(67, "\U00100001 'a' |= 'b'"))
	// Output:
	// &cc.Expression{
	// · Case: 55,
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example67.c:1:6: CHARCONST "'a'",
	// · },
	// · Expression2: &cc.Expression{
	// · · Case: 1,
	// · · Token: example67.c:1:13: CHARCONST "'b'",
	// · },
	// · Token: example67.c:1:10: ORASSIGN,
	// }
}

func ExampleExpressionList() {
	fmt.Println(exampleAST(70, "\U00100001 ( 'a' )"))
	// Output:
	// &cc.ExpressionList{
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example70.c:1:8: CHARCONST "'a'",
	// · },
	// }
}

func ExampleExpressionList_case1() {
	fmt.Println(exampleAST(71, "\U00100001 ( 'a' , 'b' )"))
	// Output:
	// &cc.ExpressionList{
	// · Expression: &cc.Expression{
	// · · Case: 1,
	// · · Token: example71.c:1:8: CHARCONST "'a'",
	// · },
	// · ExpressionList: &cc.ExpressionList{
	// · · Case: 1,
	// · · Expression: &cc.Expression{
	// · · · Case: 1,
	// · · · Token: example71.c:1:14: CHARCONST "'b'",
	// · · },
	// · · Token: example71.c:1:12: ',',
	// · },
	// }
}

func ExampleExpressionListOpt() {
	fmt.Println(exampleAST(72, "\U00100002 auto a { ;") == (*ExpressionListOpt)(nil))
	// Output:
	// true
}

func ExampleExpressionListOpt_case1() {
	fmt.Println(exampleAST(73, "\U00100002 auto a { 'b' )"))
	// Output:
	// &cc.ExpressionListOpt{
	// · ExpressionList: &cc.ExpressionList{
	// · · Type: int,
	// · · Value: 98,
	// · · Expression: &cc.Expression{
	// · · · Type: int,
	// · · · Value: 98,
	// · · · Case: 1,
	// · · · Token: example73.c:1:15: CHARCONST "'b'",
	// · · },
	// · },
	// }
}

func ExampleExpressionOpt() {
	fmt.Println(exampleAST(68, "\U00100001 ( _Bool [ ]") == (*ExpressionOpt)(nil))
	// Output:
	// true
}

func ExampleExpressionOpt_case1() {
	fmt.Println(exampleAST(69, "\U00100001 ( _Bool [ 'a' ]"))
	// Output:
	// &cc.ExpressionOpt{
	// · Expression: &cc.Expression{
	// · · Type: int,
	// · · Value: 97,
	// · · Case: 1,
	// · · Token: example69.c:1:16: CHARCONST "'a'",
	// · },
	// }
}

func ExampleExpressionStatement() {
	fmt.Println(exampleAST(219, "\U00100002 auto a { ; !"))
	// Output:
	// &cc.ExpressionStatement{
	// · Token: example219.c:1:15: ';',
	// }
}

func ExampleExternalDeclaration() {
	fmt.Println(exampleAST(233, "\U00100002 auto a { }"))
	// Output:
	// &cc.ExternalDeclaration{
	// · FunctionDefinition: &cc.FunctionDefinition{
	// · · CompoundStatement: &cc.CompoundStatement{
	// · · · Token: example233.c:1:13: '{',
	// · · · Token2: example233.c:1:15: '}',
	// · · },
	// · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · Case: 3,
	// · · · · Token: example233.c:1:6: AUTO "auto",
	// · · · },
	// · · },
	// · · Declarator: &cc.Declarator{
	// · · · Linkage: None,
	// · · · Type: auto undefined,
	// · · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · · Token: example233.c:1:11: IDENTIFIER "a",
	// · · · },
	// · · },
	// · },
	// }
}

func ExampleExternalDeclaration_case1() {
	fmt.Println(exampleAST(234, "\U00100002 auto ;"))
	// Output:
	// &cc.ExternalDeclaration{
	// · Case: 1,
	// · Declaration: &cc.Declaration{
	// · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · Case: 3,
	// · · · · Token: example234.c:1:6: AUTO "auto",
	// · · · },
	// · · },
	// · · Token: example234.c:1:11: ';',
	// · },
	// }
}

func ExampleFunctionDefinition() {
	fmt.Println(exampleAST(236, "\U00100002 auto a { }"))
	// Output:
	// &cc.FunctionDefinition{
	// · CompoundStatement: &cc.CompoundStatement{
	// · · Token: example236.c:1:13: '{',
	// · · Token2: example236.c:1:15: '}',
	// · },
	// · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · Case: 3,
	// · · · Token: example236.c:1:6: AUTO "auto",
	// · · },
	// · },
	// · Declarator: &cc.Declarator{
	// · · Linkage: None,
	// · · Type: auto undefined,
	// · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · Token: example236.c:1:11: IDENTIFIER "a",
	// · · },
	// · },
	// }
}

func ExampleFunctionSpecifier() {
	fmt.Println(exampleAST(138, "\U00100002 inline ("))
	// Output:
	// &cc.FunctionSpecifier{
	// · Token: example138.c:1:6: INLINE "inline",
	// }
}

func ExampleGroupList() {
	fmt.Println(exampleAST(242, "\U00100000 "))
	// Output:
	// &cc.GroupList{
	// }
}

func ExampleGroupList_case1() {
	fmt.Println(exampleAST(243, "\U00100000int\nf() {}"))
	// Output:
	// &cc.GroupList{
	// · GroupList: &cc.GroupList{
	// · · Case: 1,
	// · · GroupPart: []xc.Token{ // len 5
	// · · · 0: example243.c:2:1: IDENTIFIER "f",
	// · · · 1: example243.c:2:2: '(',
	// · · · 2: example243.c:2:3: ')',
	// · · · 3: example243.c:2:5: '{',
	// · · · 4: example243.c:2:6: '}',
	// · · },
	// · },
	// · GroupPart: []xc.Token{ // len 1
	// · · 0: example243.c:1:5: IDENTIFIER "int",
	// · },
	// }
}

func ExampleGroupListOpt() {
	fmt.Println(exampleAST(244, "\U00100000 \n#ifndef a  \n#elif") == (*GroupListOpt)(nil))
	// Output:
	// true
}

func ExampleGroupListOpt_case1() {
	fmt.Println(exampleAST(245, "\U00100000 \n#ifndef a\nb\n#elif"))
	// Output:
	// &cc.GroupListOpt{
	// · GroupList: &cc.GroupList{
	// · · GroupPart: []xc.Token{ // len 1
	// · · · 0: example245.c:3:1: IDENTIFIER "b",
	// · · },
	// · },
	// }
}

func ExampleIdentifierList() {
	fmt.Println(exampleAST(167, "\U00100002 auto a ( b )"))
	// Output:
	// &cc.IdentifierList{
	// · Token: example167.c:1:15: IDENTIFIER "b",
	// }
}

func ExampleIdentifierList_case1() {
	fmt.Println(exampleAST(168, "\U00100002 auto a ( b , c )"))
	// Output:
	// &cc.IdentifierList{
	// · IdentifierList: &cc.IdentifierList{
	// · · Case: 1,
	// · · Token: example168.c:1:17: ',',
	// · · Token2: example168.c:1:19: IDENTIFIER "c",
	// · },
	// · Token: example168.c:1:15: IDENTIFIER "b",
	// }
}

func ExampleIdentifierListOpt() {
	fmt.Println(exampleAST(169, "\U00100002 auto a ( )") == (*IdentifierListOpt)(nil))
	// Output:
	// true
}

func ExampleIdentifierListOpt_case1() {
	fmt.Println(exampleAST(170, "\U00100002 auto a ( b )"))
	// Output:
	// &cc.IdentifierListOpt{
	// · IdentifierList: &cc.IdentifierList{
	// · · Token: example170.c:1:15: IDENTIFIER "b",
	// · },
	// }
}

func ExampleIdentifierOpt() {
	fmt.Println(exampleAST(171, "\U00100002 struct {") == (*IdentifierOpt)(nil))
	// Output:
	// true
}

func ExampleIdentifierOpt_case1() {
	fmt.Println(exampleAST(172, "\U00100002 enum a {"))
	// Output:
	// &cc.IdentifierOpt{
	// · Token: example172.c:1:11: IDENTIFIER "a",
	// }
}

func ExampleIfGroup() {
	fmt.Println(exampleAST(251, "\U00100000 \n#if other_a  \n#elif"))
	// Output:
	// &cc.IfGroup{
	// · PPTokenList: []xc.Token{ // len 1
	// · · 0: example251.c:2:5: IDENTIFIER "other_a",
	// · },
	// · Token: example251.c:2:2: PPIF,
	// · Token2: example251.c:2:14: '\n',
	// }
}

func ExampleIfGroup_case1() {
	fmt.Println(exampleAST(252, "\U00100000 \n#ifdef a  \n#elif"))
	// Output:
	// &cc.IfGroup{
	// · Case: 1,
	// · Token: example252.c:2:2: PPIFDEF,
	// · Token2: example252.c:2:8: IDENTIFIER "a",
	// · Token3: example252.c:2:11: '\n',
	// }
}

func ExampleIfGroup_case2() {
	fmt.Println(exampleAST(253, "\U00100000 \n#ifndef a  \n#elif"))
	// Output:
	// &cc.IfGroup{
	// · Case: 2,
	// · Token: example253.c:2:2: PPIFNDEF,
	// · Token2: example253.c:2:9: IDENTIFIER "a",
	// · Token3: example253.c:2:12: '\n',
	// }
}

func ExampleIfSection() {
	fmt.Println(exampleAST(250, "\U00100000 \n#if other_a  \n#endif"))
	// Output:
	// &cc.IfSection{
	// · EndifLine: &cc.EndifLine{
	// · · Token: example250.c:3:2: PPENDIF,
	// · },
	// · IfGroup: &cc.IfGroup{
	// · · PPTokenList: []xc.Token{ // len 1
	// · · · 0: example250.c:2:5: IDENTIFIER "other_a",
	// · · },
	// · · Token: example250.c:2:2: PPIF,
	// · · Token2: example250.c:2:14: '\n',
	// · },
	// }
}

func ExampleInitDeclarator() {
	fmt.Println(exampleAST(87, "\U00100002 auto a ,"))
	// Output:
	// &cc.InitDeclarator{
	// · Declarator: &cc.Declarator{
	// · · Linkage: None,
	// · · Type: auto undefined,
	// · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · Token: example87.c:1:11: IDENTIFIER "a",
	// · · },
	// · },
	// }
}

func ExampleInitDeclarator_case1() {
	fmt.Println(exampleAST(89, "\U00100002 auto a = 'b' ,"))
	// Output:
	// &cc.InitDeclarator{
	// · Case: 1,
	// · Declarator: &cc.Declarator{
	// · · Linkage: None,
	// · · Type: auto undefined,
	// · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · Token: example89.c:1:11: IDENTIFIER "a",
	// · · },
	// · },
	// · Initializer: &cc.Initializer{
	// · · Expression: &cc.Expression{
	// · · · Type: int,
	// · · · Value: 98,
	// · · · Case: 1,
	// · · · Token: example89.c:1:15: CHARCONST "'b'",
	// · · },
	// · },
	// · Token: example89.c:1:13: '=',
	// }
}

func ExampleInitDeclaratorList() {
	fmt.Println(exampleAST(83, "\U00100002 auto a ,"))
	// Output:
	// &cc.InitDeclaratorList{
	// · InitDeclarator: &cc.InitDeclarator{
	// · · Declarator: &cc.Declarator{
	// · · · Linkage: None,
	// · · · Type: auto undefined,
	// · · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · · Token: example83.c:1:11: IDENTIFIER "a",
	// · · · },
	// · · },
	// · },
	// }
}

func ExampleInitDeclaratorList_case1() {
	fmt.Println(exampleAST(84, "\U00100002 auto a , b ,"))
	// Output:
	// &cc.InitDeclaratorList{
	// · InitDeclarator: &cc.InitDeclarator{
	// · · Declarator: &cc.Declarator{
	// · · · Linkage: None,
	// · · · Type: auto undefined,
	// · · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · · Token: example84.c:1:11: IDENTIFIER "a",
	// · · · },
	// · · },
	// · },
	// · InitDeclaratorList: &cc.InitDeclaratorList{
	// · · Case: 1,
	// · · InitDeclarator: &cc.InitDeclarator{
	// · · · Declarator: &cc.Declarator{
	// · · · · Linkage: None,
	// · · · · Type: auto undefined,
	// · · · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · · · Token: example84.c:1:15: IDENTIFIER "b",
	// · · · · },
	// · · · },
	// · · },
	// · · Token: example84.c:1:13: ',',
	// · },
	// }
}

func ExampleInitDeclaratorListOpt() {
	fmt.Println(exampleAST(85, "\U00100002 auto ;") == (*InitDeclaratorListOpt)(nil))
	// Output:
	// true
}

func ExampleInitDeclaratorListOpt_case1() {
	fmt.Println(exampleAST(86, "\U00100002 auto a ;"))
	// Output:
	// &cc.InitDeclaratorListOpt{
	// · InitDeclaratorList: &cc.InitDeclaratorList{
	// · · InitDeclarator: &cc.InitDeclarator{
	// · · · Declarator: &cc.Declarator{
	// · · · · Linkage: None,
	// · · · · Type: auto undefined,
	// · · · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · · · Token: example86.c:1:11: IDENTIFIER "a",
	// · · · · },
	// · · · },
	// · · },
	// · },
	// }
}

func ExampleInitializer() {
	fmt.Println(exampleAST(191, "\U00100002 auto a = 'b' ,"))
	// Output:
	// &cc.Initializer{
	// · Expression: &cc.Expression{
	// · · Type: int,
	// · · Value: 98,
	// · · Case: 1,
	// · · Token: example191.c:1:15: CHARCONST "'b'",
	// · },
	// }
}

func ExampleInitializer_case1() {
	fmt.Println(exampleAST(192, "\U00100002 auto a = { 'b' } ,"))
	// Output:
	// &cc.Initializer{
	// · Case: 1,
	// · InitializerList: &cc.InitializerList{
	// · · Initializer: &cc.Initializer{
	// · · · Expression: &cc.Expression{
	// · · · · Type: int,
	// · · · · Value: 98,
	// · · · · Case: 1,
	// · · · · Token: example192.c:1:17: CHARCONST "'b'",
	// · · · },
	// · · },
	// · },
	// · Token: example192.c:1:15: '{',
	// · Token2: example192.c:1:21: '}',
	// }
}

func ExampleInitializerList() {
	fmt.Println(exampleAST(193, "\U00100001 ( _Bool ) { 'a' ,"))
	// Output:
	// &cc.InitializerList{
	// · Initializer: &cc.Initializer{
	// · · Expression: &cc.Expression{
	// · · · Type: int,
	// · · · Value: 97,
	// · · · Case: 1,
	// · · · Token: example193.c:1:18: CHARCONST "'a'",
	// · · },
	// · },
	// }
}

func ExampleInitializerList_case1() {
	fmt.Println(exampleAST(194, "\U00100002 auto a = { 'b' , 'c' ,"))
	// Output:
	// &cc.InitializerList{
	// · Initializer: &cc.Initializer{
	// · · Expression: &cc.Expression{
	// · · · Type: int,
	// · · · Value: 98,
	// · · · Case: 1,
	// · · · Token: example194.c:1:17: CHARCONST "'b'",
	// · · },
	// · },
	// · InitializerList: &cc.InitializerList{
	// · · Case: 1,
	// · · Initializer: &cc.Initializer{
	// · · · Expression: &cc.Expression{
	// · · · · Type: int,
	// · · · · Value: 99,
	// · · · · Case: 1,
	// · · · · Token: example194.c:1:23: CHARCONST "'c'",
	// · · · },
	// · · },
	// · · Token: example194.c:1:21: ',',
	// · },
	// }
}

func ExampleIterationStatement() {
	fmt.Println(exampleAST(223, "\U00100002 auto a { while ( 'b' ) ; !"))
	// Output:
	// &cc.IterationStatement{
	// · ExpressionList: &cc.ExpressionList{
	// · · Type: int,
	// · · Value: 98,
	// · · Expression: &cc.Expression{
	// · · · Type: int,
	// · · · Value: 98,
	// · · · Case: 1,
	// · · · Token: example223.c:1:23: CHARCONST "'b'",
	// · · },
	// · },
	// · Statement: &cc.Statement{
	// · · Case: 2,
	// · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · Token: example223.c:1:29: ';',
	// · · },
	// · },
	// · Token: example223.c:1:15: WHILE "while",
	// · Token2: example223.c:1:21: '(',
	// · Token3: example223.c:1:27: ')',
	// }
}

func ExampleIterationStatement_case1() {
	fmt.Println(exampleAST(224, "\U00100002 auto a { do ; while ( 'b' ) ; !"))
	// Output:
	// &cc.IterationStatement{
	// · Case: 1,
	// · ExpressionList: &cc.ExpressionList{
	// · · Type: int,
	// · · Value: 98,
	// · · Expression: &cc.Expression{
	// · · · Type: int,
	// · · · Value: 98,
	// · · · Case: 1,
	// · · · Token: example224.c:1:28: CHARCONST "'b'",
	// · · },
	// · },
	// · Statement: &cc.Statement{
	// · · Case: 2,
	// · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · Token: example224.c:1:18: ';',
	// · · },
	// · },
	// · Token: example224.c:1:15: DO "do",
	// · Token2: example224.c:1:20: WHILE "while",
	// · Token3: example224.c:1:26: '(',
	// · Token4: example224.c:1:32: ')',
	// · Token5: example224.c:1:34: ';',
	// }
}

func ExampleIterationStatement_case2() {
	fmt.Println(exampleAST(225, "\U00100002 auto a { for ( ; ; ) ; !"))
	// Output:
	// &cc.IterationStatement{
	// · Case: 2,
	// · Statement: &cc.Statement{
	// · · Case: 2,
	// · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · Token: example225.c:1:27: ';',
	// · · },
	// · },
	// · Token: example225.c:1:15: FOR "for",
	// · Token2: example225.c:1:19: '(',
	// · Token3: example225.c:1:21: ';',
	// · Token4: example225.c:1:23: ';',
	// · Token5: example225.c:1:25: ')',
	// }
}

func ExampleIterationStatement_case3() {
	fmt.Println(exampleAST(226, "\U00100002 auto a { for ( auto ; ; ) ; !"))
	// Output:
	// &cc.IterationStatement{
	// · Case: 3,
	// · Declaration: &cc.Declaration{
	// · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · Case: 3,
	// · · · · Token: example226.c:1:21: AUTO "auto",
	// · · · },
	// · · },
	// · · Token: example226.c:1:26: ';',
	// · },
	// · Statement: &cc.Statement{
	// · · Case: 2,
	// · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · Token: example226.c:1:32: ';',
	// · · },
	// · },
	// · Token: example226.c:1:15: FOR "for",
	// · Token2: example226.c:1:19: '(',
	// · Token3: example226.c:1:28: ';',
	// · Token4: example226.c:1:30: ')',
	// }
}

func ExampleJumpStatement() {
	fmt.Println(exampleAST(227, "\U00100002 auto a { goto b ; !"))
	// Output:
	// &cc.JumpStatement{
	// · Token: example227.c:1:15: GOTO "goto",
	// · Token2: example227.c:1:20: IDENTIFIER "b",
	// · Token3: example227.c:1:22: ';',
	// }
}

func ExampleJumpStatement_case1() {
	fmt.Println(exampleAST(228, "\U00100002 auto a { continue ; !"))
	// Output:
	// &cc.JumpStatement{
	// · Case: 1,
	// · Token: example228.c:1:15: CONTINUE "continue",
	// · Token2: example228.c:1:24: ';',
	// }
}

func ExampleJumpStatement_case2() {
	fmt.Println(exampleAST(229, "\U00100002 auto a { break ; !"))
	// Output:
	// &cc.JumpStatement{
	// · Case: 2,
	// · Token: example229.c:1:15: BREAK "break",
	// · Token2: example229.c:1:21: ';',
	// }
}

func ExampleJumpStatement_case3() {
	fmt.Println(exampleAST(230, "\U00100002 auto a { return ; !"))
	// Output:
	// &cc.JumpStatement{
	// · Case: 3,
	// · Token: example230.c:1:15: RETURN "return",
	// · Token2: example230.c:1:22: ';',
	// }
}

func ExampleLabeledStatement() {
	fmt.Println(exampleAST(208, "\U00100002 auto a { b : ; !"))
	// Output:
	// &cc.LabeledStatement{
	// · Statement: &cc.Statement{
	// · · Case: 2,
	// · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · Token: example208.c:1:19: ';',
	// · · },
	// · },
	// · Token: example208.c:1:15: IDENTIFIER "b",
	// · Token2: example208.c:1:17: ':',
	// }
}

func ExampleLabeledStatement_case1() {
	fmt.Println(exampleAST(209, "\U00100002 auto a { case 'b' : ; !"))
	// Output:
	// &cc.LabeledStatement{
	// · Case: 1,
	// · ConstantExpression: &cc.ConstantExpression{
	// · · Type: int,
	// · · Value: 98,
	// · · Expression: &cc.Expression{
	// · · · Type: int,
	// · · · Value: 98,
	// · · · Case: 1,
	// · · · Token: example209.c:1:20: CHARCONST "'b'",
	// · · },
	// · },
	// · Statement: &cc.Statement{
	// · · Case: 2,
	// · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · Token: example209.c:1:26: ';',
	// · · },
	// · },
	// · Token: example209.c:1:15: CASE "case",
	// · Token2: example209.c:1:24: ':',
	// }
}

func ExampleLabeledStatement_case2() {
	fmt.Println(exampleAST(210, "\U00100002 auto a { default : ; !"))
	// Output:
	// &cc.LabeledStatement{
	// · Case: 2,
	// · Statement: &cc.Statement{
	// · · Case: 2,
	// · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · Token: example210.c:1:25: ';',
	// · · },
	// · },
	// · Token: example210.c:1:15: DEFAULT "default",
	// · Token2: example210.c:1:23: ':',
	// }
}

func ExampleParameterDeclaration() {
	fmt.Println(exampleAST(165, "\U00100001 ( _Bool ( auto a )"))
	// Output:
	// &cc.ParameterDeclaration{
	// · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · Case: 3,
	// · · · Token: example165.c:1:16: AUTO "auto",
	// · · },
	// · },
	// · Declarator: &cc.Declarator{
	// · · Linkage: None,
	// · · Type: auto undefined,
	// · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · Token: example165.c:1:21: IDENTIFIER "a",
	// · · },
	// · },
	// }
}

func ExampleParameterDeclaration_case1() {
	fmt.Println(exampleAST(166, "\U00100001 ( _Bool ( auto )"))
	// Output:
	// &cc.ParameterDeclaration{
	// · Case: 1,
	// · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · Case: 3,
	// · · · Token: example166.c:1:16: AUTO "auto",
	// · · },
	// · },
	// }
}

func ExampleParameterList() {
	fmt.Println(exampleAST(163, "\U00100001 ( _Bool ( auto )"))
	// Output:
	// &cc.ParameterList{
	// · ParameterDeclaration: &cc.ParameterDeclaration{
	// · · Case: 1,
	// · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · Case: 3,
	// · · · · Token: example163.c:1:16: AUTO "auto",
	// · · · },
	// · · },
	// · },
	// }
}

func ExampleParameterList_case1() {
	fmt.Println(exampleAST(164, "\U00100001 ( _Bool ( auto , auto )"))
	// Output:
	// &cc.ParameterList{
	// · ParameterDeclaration: &cc.ParameterDeclaration{
	// · · Case: 1,
	// · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · Case: 3,
	// · · · · Token: example164.c:1:16: AUTO "auto",
	// · · · },
	// · · },
	// · },
	// · ParameterList: &cc.ParameterList{
	// · · Case: 1,
	// · · ParameterDeclaration: &cc.ParameterDeclaration{
	// · · · Case: 1,
	// · · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · · Case: 3,
	// · · · · · Token: example164.c:1:23: AUTO "auto",
	// · · · · },
	// · · · },
	// · · },
	// · · Token: example164.c:1:21: ',',
	// · },
	// }
}

func ExampleParameterTypeList() {
	fmt.Println(exampleAST(159, "\U00100001 ( _Bool ( auto )"))
	// Output:
	// &cc.ParameterTypeList{
	// · ParameterList: &cc.ParameterList{
	// · · ParameterDeclaration: &cc.ParameterDeclaration{
	// · · · Case: 1,
	// · · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · · Case: 3,
	// · · · · · Token: example159.c:1:16: AUTO "auto",
	// · · · · },
	// · · · },
	// · · },
	// · },
	// }
}

func ExampleParameterTypeList_case1() {
	fmt.Println(exampleAST(160, "\U00100001 ( _Bool ( auto , ... )"))
	// Output:
	// &cc.ParameterTypeList{
	// · Case: 1,
	// · ParameterList: &cc.ParameterList{
	// · · ParameterDeclaration: &cc.ParameterDeclaration{
	// · · · Case: 1,
	// · · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · · Case: 3,
	// · · · · · Token: example160.c:1:16: AUTO "auto",
	// · · · · },
	// · · · },
	// · · },
	// · },
	// · Token: example160.c:1:21: ',',
	// · Token2: example160.c:1:23: DDD,
	// }
}

func ExampleParameterTypeListOpt() {
	fmt.Println(exampleAST(161, "\U00100001 ( _Bool ( )") == (*ParameterTypeListOpt)(nil))
	// Output:
	// true
}

func ExampleParameterTypeListOpt_case1() {
	fmt.Println(exampleAST(162, "\U00100001 ( _Bool ( auto )"))
	// Output:
	// &cc.ParameterTypeListOpt{
	// · ParameterTypeList: &cc.ParameterTypeList{
	// · · ParameterList: &cc.ParameterList{
	// · · · ParameterDeclaration: &cc.ParameterDeclaration{
	// · · · · Case: 1,
	// · · · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · · · Case: 3,
	// · · · · · · Token: example162.c:1:16: AUTO "auto",
	// · · · · · },
	// · · · · },
	// · · · },
	// · · },
	// · },
	// }
}

func ExamplePointer() {
	fmt.Println(exampleAST(151, "\U00100002 auto * ("))
	// Output:
	// &cc.Pointer{
	// · Token: example151.c:1:11: '*',
	// }
}

func ExamplePointer_case1() {
	fmt.Println(exampleAST(152, "\U00100002 auto * * ("))
	// Output:
	// &cc.Pointer{
	// · Case: 1,
	// · Pointer: &cc.Pointer{
	// · · Token: example152.c:1:13: '*',
	// · },
	// · Token: example152.c:1:11: '*',
	// }
}

func ExamplePointerOpt() {
	fmt.Println(exampleAST(153, "\U00100002 auto (") == (*PointerOpt)(nil))
	// Output:
	// true
}

func ExamplePointerOpt_case1() {
	fmt.Println(exampleAST(154, "\U00100001 ( _Bool * ("))
	// Output:
	// &cc.PointerOpt{
	// · Pointer: &cc.Pointer{
	// · · Token: example154.c:1:14: '*',
	// · },
	// }
}

func ExamplePreprocessingFile() {
	fmt.Println(exampleAST(241, "\U00100000 "))
	// Output:
	// &cc.PreprocessingFile{
	// · GroupList: &cc.GroupList{
	// · },
	// }
}

func ExampleSelectionStatement() {
	fmt.Println(exampleAST(220, "\U00100002 auto a { if ( 'b' ) ; !"))
	// Output:
	// &cc.SelectionStatement{
	// · ExpressionList: &cc.ExpressionList{
	// · · Type: int,
	// · · Value: 98,
	// · · Expression: &cc.Expression{
	// · · · Type: int,
	// · · · Value: 98,
	// · · · Case: 1,
	// · · · Token: example220.c:1:20: CHARCONST "'b'",
	// · · },
	// · },
	// · Statement: &cc.Statement{
	// · · Case: 2,
	// · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · Token: example220.c:1:26: ';',
	// · · },
	// · },
	// · Token: example220.c:1:15: IF "if",
	// · Token2: example220.c:1:18: '(',
	// · Token3: example220.c:1:24: ')',
	// }
}

func ExampleSelectionStatement_case1() {
	fmt.Println(exampleAST(221, "\U00100002 auto a { if ( 'b' ) ; else ; !"))
	// Output:
	// &cc.SelectionStatement{
	// · Case: 1,
	// · ExpressionList: &cc.ExpressionList{
	// · · Type: int,
	// · · Value: 98,
	// · · Expression: &cc.Expression{
	// · · · Type: int,
	// · · · Value: 98,
	// · · · Case: 1,
	// · · · Token: example221.c:1:20: CHARCONST "'b'",
	// · · },
	// · },
	// · Statement: &cc.Statement{
	// · · Case: 2,
	// · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · Token: example221.c:1:26: ';',
	// · · },
	// · },
	// · Statement2: &cc.Statement{
	// · · Case: 2,
	// · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · Token: example221.c:1:33: ';',
	// · · },
	// · },
	// · Token: example221.c:1:15: IF "if",
	// · Token2: example221.c:1:18: '(',
	// · Token3: example221.c:1:24: ')',
	// · Token4: example221.c:1:28: ELSE "else",
	// }
}

func ExampleSelectionStatement_case2() {
	fmt.Println(exampleAST(222, "\U00100002 auto a { switch ( 'b' ) ; !"))
	// Output:
	// &cc.SelectionStatement{
	// · Case: 2,
	// · ExpressionList: &cc.ExpressionList{
	// · · Type: int,
	// · · Value: 98,
	// · · Expression: &cc.Expression{
	// · · · Type: int,
	// · · · Value: 98,
	// · · · Case: 1,
	// · · · Token: example222.c:1:24: CHARCONST "'b'",
	// · · },
	// · },
	// · Statement: &cc.Statement{
	// · · Case: 2,
	// · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · Token: example222.c:1:30: ';',
	// · · },
	// · },
	// · Token: example222.c:1:15: SWITCH "switch",
	// · Token2: example222.c:1:22: '(',
	// · Token3: example222.c:1:28: ')',
	// }
}

func ExampleSpecifierQualifierList() {
	fmt.Println(exampleAST(118, "\U00100001 ( _Bool ("))
	// Output:
	// &cc.SpecifierQualifierList{
	// · TypeSpecifier: &cc.TypeSpecifier{
	// · · Case: 9,
	// · · Token: example118.c:1:8: BOOL "_Bool",
	// · },
	// }
}

func ExampleSpecifierQualifierList_case1() {
	fmt.Println(exampleAST(119, "\U00100001 ( const ("))
	// Output:
	// &cc.SpecifierQualifierList{
	// · Case: 1,
	// · TypeQualifier: &cc.TypeQualifier{
	// · · Token: example119.c:1:8: CONST "const",
	// · },
	// }
}

func ExampleSpecifierQualifierListOpt() {
	fmt.Println(exampleAST(120, "\U00100001 ( _Bool (") == (*SpecifierQualifierListOpt)(nil))
	// Output:
	// true
}

func ExampleSpecifierQualifierListOpt_case1() {
	fmt.Println(exampleAST(121, "\U00100001 ( const _Bool ("))
	// Output:
	// &cc.SpecifierQualifierListOpt{
	// · SpecifierQualifierList: &cc.SpecifierQualifierList{
	// · · TypeSpecifier: &cc.TypeSpecifier{
	// · · · Case: 9,
	// · · · Token: example121.c:1:14: BOOL "_Bool",
	// · · },
	// · },
	// }
}

func ExampleStatement() {
	fmt.Println(exampleAST(202, "\U00100002 auto a { default : ; !"))
	// Output:
	// &cc.Statement{
	// · LabeledStatement: &cc.LabeledStatement{
	// · · Case: 2,
	// · · Statement: &cc.Statement{
	// · · · Case: 2,
	// · · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · · Token: example202.c:1:25: ';',
	// · · · },
	// · · },
	// · · Token: example202.c:1:15: DEFAULT "default",
	// · · Token2: example202.c:1:23: ':',
	// · },
	// }
}

func ExampleStatement_case1() {
	fmt.Println(exampleAST(203, "\U00100002 auto a { { } !"))
	// Output:
	// &cc.Statement{
	// · Case: 1,
	// · CompoundStatement: &cc.CompoundStatement{
	// · · Token: example203.c:1:15: '{',
	// · · Token2: example203.c:1:17: '}',
	// · },
	// }
}

func ExampleStatement_case2() {
	fmt.Println(exampleAST(204, "\U00100002 auto a { ; !"))
	// Output:
	// &cc.Statement{
	// · Case: 2,
	// · ExpressionStatement: &cc.ExpressionStatement{
	// · · Token: example204.c:1:15: ';',
	// · },
	// }
}

func ExampleStatement_case3() {
	fmt.Println(exampleAST(205, "\U00100002 auto a { if ( 'b' ) ; !"))
	// Output:
	// &cc.Statement{
	// · Case: 3,
	// · SelectionStatement: &cc.SelectionStatement{
	// · · ExpressionList: &cc.ExpressionList{
	// · · · Type: int,
	// · · · Value: 98,
	// · · · Expression: &cc.Expression{
	// · · · · Type: int,
	// · · · · Value: 98,
	// · · · · Case: 1,
	// · · · · Token: example205.c:1:20: CHARCONST "'b'",
	// · · · },
	// · · },
	// · · Statement: &cc.Statement{
	// · · · Case: 2,
	// · · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · · Token: example205.c:1:26: ';',
	// · · · },
	// · · },
	// · · Token: example205.c:1:15: IF "if",
	// · · Token2: example205.c:1:18: '(',
	// · · Token3: example205.c:1:24: ')',
	// · },
	// }
}

func ExampleStatement_case4() {
	fmt.Println(exampleAST(206, "\U00100002 auto a { while ( 'b' ) ; !"))
	// Output:
	// &cc.Statement{
	// · Case: 4,
	// · IterationStatement: &cc.IterationStatement{
	// · · ExpressionList: &cc.ExpressionList{
	// · · · Type: int,
	// · · · Value: 98,
	// · · · Expression: &cc.Expression{
	// · · · · Type: int,
	// · · · · Value: 98,
	// · · · · Case: 1,
	// · · · · Token: example206.c:1:23: CHARCONST "'b'",
	// · · · },
	// · · },
	// · · Statement: &cc.Statement{
	// · · · Case: 2,
	// · · · ExpressionStatement: &cc.ExpressionStatement{
	// · · · · Token: example206.c:1:29: ';',
	// · · · },
	// · · },
	// · · Token: example206.c:1:15: WHILE "while",
	// · · Token2: example206.c:1:21: '(',
	// · · Token3: example206.c:1:27: ')',
	// · },
	// }
}

func ExampleStatement_case5() {
	fmt.Println(exampleAST(207, "\U00100002 auto a { break ; !"))
	// Output:
	// &cc.Statement{
	// · Case: 5,
	// · JumpStatement: &cc.JumpStatement{
	// · · Case: 2,
	// · · Token: example207.c:1:15: BREAK "break",
	// · · Token2: example207.c:1:21: ';',
	// · },
	// }
}

func ExampleStorageClassSpecifier() {
	fmt.Println(exampleAST(90, "\U00100002 typedef ("))
	// Output:
	// &cc.StorageClassSpecifier{
	// · Token: example90.c:1:6: TYPEDEF "typedef",
	// }
}

func ExampleStorageClassSpecifier_case1() {
	fmt.Println(exampleAST(91, "\U00100002 extern ("))
	// Output:
	// &cc.StorageClassSpecifier{
	// · Case: 1,
	// · Token: example91.c:1:6: EXTERN "extern",
	// }
}

func ExampleStorageClassSpecifier_case2() {
	fmt.Println(exampleAST(92, "\U00100002 static ("))
	// Output:
	// &cc.StorageClassSpecifier{
	// · Case: 2,
	// · Token: example92.c:1:6: STATIC "static",
	// }
}

func ExampleStorageClassSpecifier_case3() {
	fmt.Println(exampleAST(93, "\U00100002 auto ("))
	// Output:
	// &cc.StorageClassSpecifier{
	// · Case: 3,
	// · Token: example93.c:1:6: AUTO "auto",
	// }
}

func ExampleStorageClassSpecifier_case4() {
	fmt.Println(exampleAST(94, "\U00100002 register ("))
	// Output:
	// &cc.StorageClassSpecifier{
	// · Case: 4,
	// · Token: example94.c:1:6: REGISTER "register",
	// }
}

func ExampleStructDeclaration() {
	fmt.Println(exampleAST(117, "\U00100002 struct { _Bool a ; }"))
	// Output:
	// &cc.StructDeclaration{
	// · SpecifierQualifierList: &cc.SpecifierQualifierList{
	// · · TypeSpecifier: &cc.TypeSpecifier{
	// · · · Case: 9,
	// · · · Token: example117.c:1:15: BOOL "_Bool",
	// · · },
	// · },
	// · StructDeclaratorList: &cc.StructDeclaratorList{
	// · · StructDeclarator: &cc.StructDeclarator{
	// · · · Declarator: &cc.Declarator{
	// · · · · Linkage: None,
	// · · · · Type: bool,
	// · · · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · · · Token: example117.c:1:21: IDENTIFIER "a",
	// · · · · },
	// · · · },
	// · · },
	// · },
	// · Token: example117.c:1:23: ';',
	// }
}

func ExampleStructDeclarationList() {
	fmt.Println(exampleAST(115, "\U00100002 struct { _Bool a ; }"))
	// Output:
	// &cc.StructDeclarationList{
	// · StructDeclaration: &cc.StructDeclaration{
	// · · SpecifierQualifierList: &cc.SpecifierQualifierList{
	// · · · TypeSpecifier: &cc.TypeSpecifier{
	// · · · · Case: 9,
	// · · · · Token: example115.c:1:15: BOOL "_Bool",
	// · · · },
	// · · },
	// · · StructDeclaratorList: &cc.StructDeclaratorList{
	// · · · StructDeclarator: &cc.StructDeclarator{
	// · · · · Declarator: &cc.Declarator{
	// · · · · · Linkage: None,
	// · · · · · Type: bool,
	// · · · · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · · · · Token: example115.c:1:21: IDENTIFIER "a",
	// · · · · · },
	// · · · · },
	// · · · },
	// · · },
	// · · Token: example115.c:1:23: ';',
	// · },
	// }
}

func ExampleStructDeclarationList_case1() {
	fmt.Println(exampleAST(116, "\U00100002 struct { _Bool a ; _Bool b ; }"))
	// Output:
	// &cc.StructDeclarationList{
	// · StructDeclaration: &cc.StructDeclaration{
	// · · SpecifierQualifierList: &cc.SpecifierQualifierList{
	// · · · TypeSpecifier: &cc.TypeSpecifier{
	// · · · · Case: 9,
	// · · · · Token: example116.c:1:15: BOOL "_Bool",
	// · · · },
	// · · },
	// · · StructDeclaratorList: &cc.StructDeclaratorList{
	// · · · StructDeclarator: &cc.StructDeclarator{
	// · · · · Declarator: &cc.Declarator{
	// · · · · · Linkage: None,
	// · · · · · Type: bool,
	// · · · · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · · · · Token: example116.c:1:21: IDENTIFIER "a",
	// · · · · · },
	// · · · · },
	// · · · },
	// · · },
	// · · Token: example116.c:1:23: ';',
	// · },
	// · StructDeclarationList: &cc.StructDeclarationList{
	// · · Case: 1,
	// · · StructDeclaration: &cc.StructDeclaration{
	// · · · SpecifierQualifierList: &cc.SpecifierQualifierList{
	// · · · · TypeSpecifier: &cc.TypeSpecifier{
	// · · · · · Case: 9,
	// · · · · · Token: example116.c:1:25: BOOL "_Bool",
	// · · · · },
	// · · · },
	// · · · StructDeclaratorList: &cc.StructDeclaratorList{
	// · · · · StructDeclarator: &cc.StructDeclarator{
	// · · · · · Declarator: &cc.Declarator{
	// · · · · · · Linkage: None,
	// · · · · · · Type: bool,
	// · · · · · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · · · · · Token: example116.c:1:31: IDENTIFIER "b",
	// · · · · · · },
	// · · · · · },
	// · · · · },
	// · · · },
	// · · · Token: example116.c:1:33: ';',
	// · · },
	// · },
	// }
}

func ExampleStructDeclarator() {
	fmt.Println(exampleAST(124, "\U00100002 struct { _Bool a ,"))
	// Output:
	// &cc.StructDeclarator{
	// · Declarator: &cc.Declarator{
	// · · Linkage: None,
	// · · Type: bool,
	// · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · Token: example124.c:1:21: IDENTIFIER "a",
	// · · },
	// · },
	// }
}

func ExampleStructDeclarator_case1() {
	fmt.Println(exampleAST(125, "\U00100002 struct { _Bool : 'a' ,"))
	// Output:
	// &cc.StructDeclarator{
	// · Case: 1,
	// · ConstantExpression: &cc.ConstantExpression{
	// · · Type: int,
	// · · Value: 97,
	// · · Expression: &cc.Expression{
	// · · · Type: int,
	// · · · Value: 97,
	// · · · Case: 1,
	// · · · Token: example125.c:1:23: CHARCONST "'a'",
	// · · },
	// · },
	// · Token: example125.c:1:21: ':',
	// }
}

func ExampleStructDeclaratorList() {
	fmt.Println(exampleAST(122, "\U00100002 struct { _Bool a ,"))
	// Output:
	// &cc.StructDeclaratorList{
	// · StructDeclarator: &cc.StructDeclarator{
	// · · Declarator: &cc.Declarator{
	// · · · Linkage: None,
	// · · · Type: bool,
	// · · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · · Token: example122.c:1:21: IDENTIFIER "a",
	// · · · },
	// · · },
	// · },
	// }
}

func ExampleStructDeclaratorList_case1() {
	fmt.Println(exampleAST(123, "\U00100002 struct { _Bool a , b ,"))
	// Output:
	// &cc.StructDeclaratorList{
	// · StructDeclarator: &cc.StructDeclarator{
	// · · Declarator: &cc.Declarator{
	// · · · Linkage: None,
	// · · · Type: bool,
	// · · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · · Token: example123.c:1:21: IDENTIFIER "a",
	// · · · },
	// · · },
	// · },
	// · StructDeclaratorList: &cc.StructDeclaratorList{
	// · · Case: 1,
	// · · StructDeclarator: &cc.StructDeclarator{
	// · · · Declarator: &cc.Declarator{
	// · · · · Linkage: None,
	// · · · · Type: bool,
	// · · · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · · · Token: example123.c:1:25: IDENTIFIER "b",
	// · · · · },
	// · · · },
	// · · },
	// · · Token: example123.c:1:23: ',',
	// · },
	// }
}

func ExampleStructOrUnion() {
	fmt.Println(exampleAST(113, "\U00100002 struct {"))
	// Output:
	// &cc.StructOrUnion{
	// · Token: example113.c:1:6: STRUCT "struct",
	// }
}

func ExampleStructOrUnion_case1() {
	fmt.Println(exampleAST(114, "\U00100002 union {"))
	// Output:
	// &cc.StructOrUnion{
	// · Case: 1,
	// · Token: example114.c:1:6: UNION "union",
	// }
}

func ExampleStructOrUnionSpecifier() {
	fmt.Println(exampleAST(111, "\U00100002 struct { _Bool a ; } ("))
	// Output:
	// &cc.StructOrUnionSpecifier{
	// · StructDeclarationList: &cc.StructDeclarationList{
	// · · StructDeclaration: &cc.StructDeclaration{
	// · · · SpecifierQualifierList: &cc.SpecifierQualifierList{
	// · · · · TypeSpecifier: &cc.TypeSpecifier{
	// · · · · · Case: 9,
	// · · · · · Token: example111.c:1:15: BOOL "_Bool",
	// · · · · },
	// · · · },
	// · · · StructDeclaratorList: &cc.StructDeclaratorList{
	// · · · · StructDeclarator: &cc.StructDeclarator{
	// · · · · · Declarator: &cc.Declarator{
	// · · · · · · Linkage: None,
	// · · · · · · Type: bool,
	// · · · · · · DirectDeclarator: &cc.DirectDeclarator{
	// · · · · · · · Token: example111.c:1:21: IDENTIFIER "a",
	// · · · · · · },
	// · · · · · },
	// · · · · },
	// · · · },
	// · · · Token: example111.c:1:23: ';',
	// · · },
	// · },
	// · StructOrUnion: &cc.StructOrUnion{
	// · · Token: example111.c:1:6: STRUCT "struct",
	// · },
	// · Token: example111.c:1:13: '{',
	// · Token2: example111.c:1:25: '}',
	// }
}

func ExampleStructOrUnionSpecifier_case1() {
	fmt.Println(exampleAST(112, "\U00100002 struct a ("))
	// Output:
	// &cc.StructOrUnionSpecifier{
	// · Case: 1,
	// · StructOrUnion: &cc.StructOrUnion{
	// · · Token: example112.c:1:6: STRUCT "struct",
	// · },
	// · Token: example112.c:1:13: IDENTIFIER "a",
	// }
}

func ExampleTranslationUnit() {
	fmt.Println(exampleAST(231, "\U00100002 auto ;"))
	// Output:
	// &cc.TranslationUnit{
	// · ExternalDeclaration: &cc.ExternalDeclaration{
	// · · Case: 1,
	// · · Declaration: &cc.Declaration{
	// · · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · · Case: 3,
	// · · · · · Token: example231.c:1:6: AUTO "auto",
	// · · · · },
	// · · · },
	// · · · Token: example231.c:1:11: ';',
	// · · },
	// · },
	// }
}

func ExampleTranslationUnit_case1() {
	fmt.Println(exampleAST(232, "\U00100002 auto ; auto ;"))
	// Output:
	// &cc.TranslationUnit{
	// · ExternalDeclaration: &cc.ExternalDeclaration{
	// · · Case: 1,
	// · · Declaration: &cc.Declaration{
	// · · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · · Case: 3,
	// · · · · · Token: example232.c:1:6: AUTO "auto",
	// · · · · },
	// · · · },
	// · · · Token: example232.c:1:11: ';',
	// · · },
	// · },
	// · TranslationUnit: &cc.TranslationUnit{
	// · · Case: 1,
	// · · ExternalDeclaration: &cc.ExternalDeclaration{
	// · · · Case: 1,
	// · · · Declaration: &cc.Declaration{
	// · · · · DeclarationSpecifiers: &cc.DeclarationSpecifiers{
	// · · · · · StorageClassSpecifier: &cc.StorageClassSpecifier{
	// · · · · · · Case: 3,
	// · · · · · · Token: example232.c:1:13: AUTO "auto",
	// · · · · · },
	// · · · · },
	// · · · · Token: example232.c:1:18: ';',
	// · · · },
	// · · },
	// · },
	// }
}

func ExampleTypeName() {
	fmt.Println(exampleAST(174, "\U00100001 ( _Bool )"))
	// Output:
	// &cc.TypeName{
	// · Type: bool,
	// · SpecifierQualifierList: &cc.SpecifierQualifierList{
	// · · TypeSpecifier: &cc.TypeSpecifier{
	// · · · Case: 9,
	// · · · Token: example174.c:1:8: BOOL "_Bool",
	// · · },
	// · },
	// }
}

func ExampleTypeQualifier() {
	fmt.Println(exampleAST(135, "\U00100002 const !"))
	// Output:
	// &cc.TypeQualifier{
	// · Token: example135.c:1:6: CONST "const",
	// }
}

func ExampleTypeQualifier_case1() {
	fmt.Println(exampleAST(136, "\U00100002 restrict !"))
	// Output:
	// &cc.TypeQualifier{
	// · Case: 1,
	// · Token: example136.c:1:6: RESTRICT "restrict",
	// }
}

func ExampleTypeQualifier_case2() {
	fmt.Println(exampleAST(137, "\U00100002 volatile !"))
	// Output:
	// &cc.TypeQualifier{
	// · Case: 2,
	// · Token: example137.c:1:6: VOLATILE "volatile",
	// }
}

func ExampleTypeQualifierList() {
	fmt.Println(exampleAST(155, "\U00100002 auto * const !"))
	// Output:
	// &cc.TypeQualifierList{
	// · TypeQualifier: &cc.TypeQualifier{
	// · · Token: example155.c:1:13: CONST "const",
	// · },
	// }
}

func ExampleTypeQualifierList_case1() {
	fmt.Println(exampleAST(156, "\U00100002 auto * const const !"))
	// Output:
	// &cc.TypeQualifierList{
	// · TypeQualifier: &cc.TypeQualifier{
	// · · Token: example156.c:1:13: CONST "const",
	// · },
	// · TypeQualifierList: &cc.TypeQualifierList{
	// · · Case: 1,
	// · · TypeQualifier: &cc.TypeQualifier{
	// · · · Token: example156.c:1:19: CONST "const",
	// · · },
	// · },
	// }
}

func ExampleTypeQualifierListOpt() {
	fmt.Println(exampleAST(157, "\U00100002 auto * (") == (*TypeQualifierListOpt)(nil))
	// Output:
	// true
}

func ExampleTypeQualifierListOpt_case1() {
	fmt.Println(exampleAST(158, "\U00100002 auto * const !"))
	// Output:
	// &cc.TypeQualifierListOpt{
	// · TypeQualifierList: &cc.TypeQualifierList{
	// · · TypeQualifier: &cc.TypeQualifier{
	// · · · Token: example158.c:1:13: CONST "const",
	// · · },
	// · },
	// }
}

func ExampleTypeSpecifier() {
	fmt.Println(exampleAST(95, "\U00100002 void ("))
	// Output:
	// &cc.TypeSpecifier{
	// · Token: example95.c:1:6: VOID "void",
	// }
}

func ExampleTypeSpecifier_case01() {
	fmt.Println(exampleAST(96, "\U00100002 char ("))
	// Output:
	// &cc.TypeSpecifier{
	// · Case: 1,
	// · Token: example96.c:1:6: CHAR "char",
	// }
}

func ExampleTypeSpecifier_case02() {
	fmt.Println(exampleAST(97, "\U00100002 short ("))
	// Output:
	// &cc.TypeSpecifier{
	// · Case: 2,
	// · Token: example97.c:1:6: SHORT "short",
	// }
}

func ExampleTypeSpecifier_case03() {
	fmt.Println(exampleAST(98, "\U00100002 int ("))
	// Output:
	// &cc.TypeSpecifier{
	// · Case: 3,
	// · Token: example98.c:1:6: INT "int",
	// }
}

func ExampleTypeSpecifier_case04() {
	fmt.Println(exampleAST(99, "\U00100002 long ("))
	// Output:
	// &cc.TypeSpecifier{
	// · Case: 4,
	// · Token: example99.c:1:6: LONG "long",
	// }
}

func ExampleTypeSpecifier_case05() {
	fmt.Println(exampleAST(100, "\U00100002 float ("))
	// Output:
	// &cc.TypeSpecifier{
	// · Case: 5,
	// · Token: example100.c:1:6: FLOAT "float",
	// }
}

func ExampleTypeSpecifier_case06() {
	fmt.Println(exampleAST(101, "\U00100002 double ("))
	// Output:
	// &cc.TypeSpecifier{
	// · Case: 6,
	// · Token: example101.c:1:6: DOUBLE "double",
	// }
}

func ExampleTypeSpecifier_case07() {
	fmt.Println(exampleAST(102, "\U00100002 signed ("))
	// Output:
	// &cc.TypeSpecifier{
	// · Case: 7,
	// · Token: example102.c:1:6: SIGNED "signed",
	// }
}

func ExampleTypeSpecifier_case08() {
	fmt.Println(exampleAST(103, "\U00100002 unsigned ("))
	// Output:
	// &cc.TypeSpecifier{
	// · Case: 8,
	// · Token: example103.c:1:6: UNSIGNED "unsigned",
	// }
}

func ExampleTypeSpecifier_case09() {
	fmt.Println(exampleAST(104, "\U00100002 _Bool ("))
	// Output:
	// &cc.TypeSpecifier{
	// · Case: 9,
	// · Token: example104.c:1:6: BOOL "_Bool",
	// }
}

func ExampleTypeSpecifier_case10() {
	fmt.Println(exampleAST(105, "\U00100002 _Complex ("))
	// Output:
	// &cc.TypeSpecifier{
	// · Case: 10,
	// · Token: example105.c:1:6: COMPLEX "_Complex",
	// }
}

func ExampleTypeSpecifier_case11() {
	fmt.Println(exampleAST(106, "\U00100002 struct a ("))
	// Output:
	// &cc.TypeSpecifier{
	// · Case: 11,
	// · StructOrUnionSpecifier: &cc.StructOrUnionSpecifier{
	// · · Case: 1,
	// · · StructOrUnion: &cc.StructOrUnion{
	// · · · Token: example106.c:1:6: STRUCT "struct",
	// · · },
	// · · Token: example106.c:1:13: IDENTIFIER "a",
	// · },
	// }
}

func ExampleTypeSpecifier_case12() {
	fmt.Println(exampleAST(107, "\U00100002 enum a ("))
	// Output:
	// &cc.TypeSpecifier{
	// · Case: 12,
	// · EnumSpecifier: &cc.EnumSpecifier{
	// · · Case: 1,
	// · · Token: example107.c:1:6: ENUM "enum",
	// · · Token2: example107.c:1:11: IDENTIFIER "a",
	// · },
	// }
}

func ExampleTypeSpecifier_case13() {
	fmt.Println(exampleAST(108, "\U00100002 typedef int i; i j;"))
	// Output:
	// &cc.TypeSpecifier{
	// · Case: 13,
	// · Token: example108.c:1:21: TYPEDEFNAME "i",
	// }
}
