// Code generated by "stringer -output stringer.go -linecomment -type=Kind,Linkage"; DO NOT EDIT.

package cc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Array-1]
	_ = x[Bool-2]
	_ = x[Char-3]
	_ = x[ComplexChar-4]
	_ = x[ComplexDouble-5]
	_ = x[ComplexFloat-6]
	_ = x[ComplexInt-7]
	_ = x[ComplexLong-8]
	_ = x[ComplexLongDouble-9]
	_ = x[ComplexLongLong-10]
	_ = x[ComplexShort-11]
	_ = x[ComplexUInt-12]
	_ = x[ComplexULong-13]
	_ = x[ComplexULongLong-14]
	_ = x[ComplexUShort-15]
	_ = x[Decimal128-16]
	_ = x[Decimal32-17]
	_ = x[Decimal64-18]
	_ = x[Double-19]
	_ = x[Enum-20]
	_ = x[Float-21]
	_ = x[Float128-22]
	_ = x[Float32-23]
	_ = x[Float32x-24]
	_ = x[Float64-25]
	_ = x[Float64x-26]
	_ = x[Function-27]
	_ = x[Int-28]
	_ = x[Int128-29]
	_ = x[Long-30]
	_ = x[LongDouble-31]
	_ = x[LongLong-32]
	_ = x[Ptr-33]
	_ = x[SChar-34]
	_ = x[Short-35]
	_ = x[Struct-36]
	_ = x[TypedefName-37]
	_ = x[UChar-38]
	_ = x[UInt-39]
	_ = x[UInt128-40]
	_ = x[ULong-41]
	_ = x[ULongLong-42]
	_ = x[UShort-43]
	_ = x[Union-44]
	_ = x[Void-45]
	_ = x[typeofExpr-46]
	_ = x[typeofType-47]
	_ = x[maxKind-48]
}

const _Kind_name = "InvalidT[]_Boolcharcomplex charcomplex doublecomplex floatcomplex intcomplex longcomplex long doublecomplex long longcomplex shortcomplex unsignedcomplex unsigned longcomplex unsigned long longcomplex shor_Decimal128_Decimal32_Decimal64doubleenumfloat_Float128_Float32_Float32x_Float64_Float64xfunctionint__int128longlong doublelong longpointersigned charshortstructtypedefnameunsigned charunsignedunsigned __int128unsigned longunsigned long longunsigned shortunionvoidtypeofExprtypeofTypemaxKind"

var _Kind_index = [...]uint16{0, 7, 10, 15, 19, 31, 45, 58, 69, 81, 100, 117, 130, 146, 167, 193, 205, 216, 226, 236, 242, 246, 251, 260, 268, 277, 285, 294, 302, 305, 313, 317, 328, 337, 344, 355, 360, 366, 377, 390, 398, 415, 428, 446, 460, 465, 469, 479, 489, 496}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Internal-1]
	_ = x[External-2]
}

const _Linkage_name = "NoneInternalExternal"

var _Linkage_index = [...]uint8{0, 4, 12, 20}

func (i Linkage) String() string {
	if i < 0 || i >= Linkage(len(_Linkage_index)-1) {
		return "Linkage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Linkage_name[_Linkage_index[i]:_Linkage_index[i+1]]
}
